import type { BlogPost } from '@/blog-data/types';

/** Part 2 articles 26–50 — biorevitalization */

export const biorevitalizationArticlesPart2: BlogPost[] = [
  {
    id: 'biorevitalizaciya-zona-periorbit',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-zona-periorbit-beltsy',
    slugRo: 'biorevitalizare-periorbitar-balti',
    publishedAt: '2026-10-09',
    dateModified: '2026-10-09',
    titleRu: 'Биоревитализация периорбитально | Meddera',
    titleRo: 'Biorevitalizare periorbitală | Meddera',
    descriptionRu: 'Биоревитализация периорбитально: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Biorevitalizare periorbitală: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: биоревитализация периорбитально.',
    excerptRo: 'Pe scurt: biorevitalizare periorbitală.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-zona-sheya',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-zona-sheya-beltsy',
    slugRo: 'biorevitalizare-gat-balti',
    publishedAt: '2026-10-10',
    dateModified: '2026-10-10',
    titleRu: 'Биоревитализация шеи | Meddera',
    titleRo: 'Biorevitalizarea gâtului | Meddera',
    descriptionRu: 'Биоревитализация шеи: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Biorevitalizarea gâtului: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: биоревитализация шеи.',
    excerptRo: 'Pe scurt: biorevitalizarea gâtului.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-zona-dekolte',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-zona-dekolte-beltsy',
    slugRo: 'biorevitalizare-decolteu-balti',
    publishedAt: '2026-10-11',
    dateModified: '2026-10-11',
    titleRu: 'Биоревитализация декольте | Meddera',
    titleRo: 'Biorevitalizarea decolteului | Meddera',
    descriptionRu: 'Биоревитализация декольте: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Biorevitalizarea decolteului: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: биоревитализация декольте.',
    excerptRo: 'Pe scurt: biorevitalizarea decolteului.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-kurs-nakopitelnyj',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-kurs-nakopitelnyj-beltsy',
    slugRo: 'biorevitalizare-curs-cumulativ-balti',
    publishedAt: '2026-10-12',
    dateModified: '2026-10-12',
    titleRu: 'Накопительный эффект курса | Meddera',
    titleRo: 'Efect cumulativ al cursului | Meddera',
    descriptionRu: 'Накопительный эффект курса: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Efect cumulativ al cursului: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: накопительный эффект курса.',
    excerptRo: 'Pe scurt: efect cumulativ al cursului.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-vysokaya-koncentraciya',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-vysokaya-koncentraciya-beltsy',
    slugRo: 'biorevitalizare-concentratie-mare-balti',
    publishedAt: '2026-10-13',
    dateModified: '2026-10-13',
    titleRu: 'Высокая концентрация ГК | Meddera',
    titleRo: 'Concentrație mare de AH | Meddera',
    descriptionRu: 'Высокая концентрация ГК: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Concentrație mare de AH: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: высокая концентрация гк.',
    excerptRo: 'Pe scurt: concentrație mare de ah.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-nizkaya-koncentraciya',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-nizkaya-koncentraciya-beltsy',
    slugRo: 'biorevitalizare-concentratie-mica-balti',
    publishedAt: '2026-10-14',
    dateModified: '2026-10-14',
    titleRu: 'Мягкий протокол | Meddera',
    titleRo: 'Protocol blând | Meddera',
    descriptionRu: 'Мягкий протокол: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Protocol blând: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: мягкий протокол.',
    excerptRo: 'Pe scurt: protocol blând.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-posle-puteshestviya',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-posle-puteshestviya-beltsy',
    slugRo: 'biorevitalizare-dupa-calatorie-balti',
    publishedAt: '2026-10-15',
    dateModified: '2026-10-15',
    titleRu: 'После перелётов и сухого климата | Meddera',
    titleRo: 'După zbor și climat uscat | Meddera',
    descriptionRu: 'После перелётов и сухого климата: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'După zbor și climat uscat: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: после перелётов и сухого климата.',
    excerptRo: 'Pe scurt: după zbor și climat uscat.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-i-kontur-chitat',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-i-kontur-chitat-beltsy',
    slugRo: 'biorevitalizare-contur-complet-balti',
    publishedAt: '2026-10-16',
    dateModified: '2026-10-16',
    titleRu: 'Сочетание с контуром | Meddera',
    titleRo: 'Combinare cu conturarea | Meddera',
    descriptionRu: 'Сочетание с контуром: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Combinare cu conturarea: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: сочетание с контуром.',
    excerptRo: 'Pe scurt: combinare cu conturarea.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-i-botoks-logika',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-i-botoks-logika-beltsy',
    slugRo: 'biorevitalizare-botox-logica-balti',
    publishedAt: '2026-10-17',
    dateModified: '2026-10-17',
    titleRu: 'Ботокс и биоревитализация | Meddera',
    titleRo: 'Botox și biorevitalizare | Meddera',
    descriptionRu: 'Ботокс и биоревитализация: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox și biorevitalizare: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс и биоревитализация.',
    excerptRo: 'Pe scurt: botox și biorevitalizare.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-i-peeling-interval',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-i-peeling-interval-beltsy',
    slugRo: 'biorevitalizare-peeling-interval-balti',
    publishedAt: '2026-10-18',
    dateModified: '2026-10-18',
    titleRu: 'Интервал после пилинга | Meddera',
    titleRo: 'Interval după peeling | Meddera',
    descriptionRu: 'Интервал после пилинга: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Interval după peeling: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: интервал после пилинга.',
    excerptRo: 'Pe scurt: interval după peeling.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-zimoi-vlaga',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-zimoi-vlaga-beltsy',
    slugRo: 'biorevitalizare-iarna-umiditate-balti',
    publishedAt: '2026-10-19',
    dateModified: '2026-10-19',
    titleRu: 'Зимняя гидратация | Meddera',
    titleRo: 'Hidratare iarnă | Meddera',
    descriptionRu: 'Зимняя гидратация: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Hidratare iarnă: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: зимняя гидратация.',
    excerptRo: 'Pe scurt: hidratare iarnă.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-letom-spf',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-letom-spf-beltsy',
    slugRo: 'biorevitalizare-vara-spf-balti',
    publishedAt: '2026-10-20',
    dateModified: '2026-10-20',
    titleRu: 'Лето и SPF | Meddera',
    titleRo: 'Vară și SPF | Meddera',
    descriptionRu: 'Лето и SPF: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Vară și SPF: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: лето и spf.',
    excerptRo: 'Pe scurt: vară și spf.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-kozha-sklonnaya-akne',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-kozha-sklonnaya-akne-beltsy',
    slugRo: 'biorevitalizare-piele-tendinta-acnee-balti',
    publishedAt: '2026-10-21',
    dateModified: '2026-10-21',
    titleRu: 'Кожа склонная к акне | Meddera',
    titleRo: 'Pielea predispusă la acnee | Meddera',
    descriptionRu: 'Кожа склонная к акне: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Pielea predispusă la acnee: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: кожа склонная к акне.',
    excerptRo: 'Pe scurt: pielea predispusă la acnee.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-post-vospaleniya',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizacia-post-vospaleniya-beltsy',
    slugRo: 'biorevitalizare-post-inflamatie-balti',
    publishedAt: '2026-10-22',
    dateModified: '2026-10-22',
    titleRu: 'После воспалений | Meddera',
    titleRo: 'După inflamații | Meddera',
    descriptionRu: 'После воспалений: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'După inflamații: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: после воспалений.',
    excerptRo: 'Pe scurt: după inflamații.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-tonkaja-kozha',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-tonkaja-kozha-beltsy',
    slugRo: 'biorevitalizare-piele-subtire-balti',
    publishedAt: '2026-10-23',
    dateModified: '2026-10-23',
    titleRu: 'Тонкая кожа | Meddera',
    titleRo: 'Pielea subțire | Meddera',
    descriptionRu: 'Тонкая кожа: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Pielea subțire: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: тонкая кожа.',
    excerptRo: 'Pe scurt: pielea subțire.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-zrelaja-kozha',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-zrelaja-kozha-beltsy',
    slugRo: 'biorevitalizare-piele-matura-balti',
    publishedAt: '2026-10-24',
    dateModified: '2026-10-24',
    titleRu: 'Зрелая кожа | Meddera',
    titleRo: 'Pielea matură | Meddera',
    descriptionRu: 'Зрелая кожа: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Pielea matură: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: зрелая кожа.',
    excerptRo: 'Pe scurt: pielea matură.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-pervyj-kurs',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-pervyj-kurs-beltsy',
    slugRo: 'biorevitalizare-primul-curs-balti',
    publishedAt: '2026-10-25',
    dateModified: '2026-10-25',
    titleRu: 'Первый курс | Meddera',
    titleRo: 'Primul curs | Meddera',
    descriptionRu: 'Первый курс: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Primul curs: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: первый курс.',
    excerptRo: 'Pe scurt: primul curs.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-vtoroj-kurs',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-vtoroj-kurs-beltsy',
    slugRo: 'biorevitalizare-al-doilea-curs-balti',
    publishedAt: '2026-10-26',
    dateModified: '2026-10-26',
    titleRu: 'Повторный курс | Meddera',
    titleRo: 'Al doilea curs | Meddera',
    descriptionRu: 'Повторный курс: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Al doilea curs: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: повторный курс.',
    excerptRo: 'Pe scurt: al doilea curs.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-kontrol-data',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-kontrol-data-beltsy',
    slugRo: 'biorevitalizare-data-control-balti',
    publishedAt: '2026-10-27',
    dateModified: '2026-10-27',
    titleRu: 'Контрольная дата | Meddera',
    titleRo: 'Data de control | Meddera',
    descriptionRu: 'Контрольная дата: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Data de control: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: контрольная дата.',
    excerptRo: 'Pe scurt: data de control.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-senzacii-posle',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-senzacii-posle-beltsy',
    slugRo: 'biorevitalizare-senzatii-dupa-balti',
    publishedAt: '2026-10-28',
    dateModified: '2026-10-28',
    titleRu: 'Ощущения после процедуры | Meddera',
    titleRo: 'Senzații după procedură | Meddera',
    descriptionRu: 'Ощущения после процедуры: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Senzații după procedură: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ощущения после процедуры.',
    excerptRo: 'Pe scurt: senzații după procedură.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-protivopokazaniya-kratko',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-protivopokazaniya-kratko-beltsy',
    slugRo: 'biorevitalizare-contraindicatii-scurt-balti',
    publishedAt: '2026-10-29',
    dateModified: '2026-10-29',
    titleRu: 'Кратко о противопоказаниях | Meddera',
    titleRo: 'Scurt despre contraindicații | Meddera',
    descriptionRu: 'Кратко о противопоказаниях: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Scurt despre contraindicații: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: кратко о противопоказаниях.',
    excerptRo: 'Pe scurt: scurt despre contraindicații.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-ocherednost-s-drugimi',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-ocherednost-s-drugimi-beltsy',
    slugRo: 'biorevitalizare-ordine-alte-proceduri-balti',
    publishedAt: '2026-10-30',
    dateModified: '2026-10-30',
    titleRu: 'Очерёдность с другими процедuri | Meddera',
    titleRo: 'Ordinea cu alte proceduri | Meddera',
    descriptionRu: 'Очерёдность с другими процедuri: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Ordinea cu alte proceduri: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: очерёдность с другими процедuri.',
    excerptRo: 'Pe scurt: ordinea cu alte proceduri.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-reabilitaciya-posle-solnca',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-reabilitaciya-posle-solnca-beltsy',
    slugRo: 'biorevitalizare-reabilitare-dupa-soare-balti',
    publishedAt: '2026-10-31',
    dateModified: '2026-10-31',
    titleRu: 'Реабилитация после загара | Meddera',
    titleRo: 'Reabilitare după soare | Meddera',
    descriptionRu: 'Реабилитация после загара: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Reabilitare după soare: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: реабилитация после загара.',
    excerptRo: 'Pe scurt: reabilitare după soare.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-zapis-konsultaciya',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-zapis-konsultaciya-beltsy',
    slugRo: 'biorevitalizare-programare-consultatie-balti',
    publishedAt: '2026-11-01',
    dateModified: '2026-11-01',
    titleRu: 'Запись на биоревитализацию | Meddera',
    titleRo: 'Programare biorevitalizare | Meddera',
    descriptionRu: 'Запись на биоревитализацию: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Programare biorevitalizare: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: запись на биоревитализацию.',
    excerptRo: 'Pe scurt: programare biorevitalizare.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'biorevitalizaciya-ingrijire-dom-kombinat',
    kind: 'article',
    clusterId: 'biorevitalization',
    slugRu: 'biorevitalizaciya-ingrijire-dom-kombinat-beltsy',
    slugRo: 'biorevitalizare-ingrijire-acasa-combinata-balti',
    publishedAt: '2026-11-02',
    dateModified: '2026-11-02',
    titleRu: 'Домашний уход после курса | Meddera',
    titleRo: 'Îngrijire acasă după curs | Meddera',
    descriptionRu: 'Домашний уход после курса: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Îngrijire acasă după curs: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: домашний уход после курса.',
    excerptRo: 'Pe scurt: îngrijire acasă după curs.',
    bodyKey: 'biorevitalization-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
];
