import type { BlogPost } from '@/blog-data/types';

/**
 * Рубрика "Ботокс в Бельцах" — часть 1 (статьи 1-25)
 */

export const botoxArticlesPart1: BlogPost[] = [
  {
    id: 'botoks-beltsy-chto-nuzhno-znat',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-beltsy-chto-nuzhno-znat-pered-proceduroy',
    slugRo: 'botox-balti-ce-trebuie-sa-stiti-inainte-procedura',
    publishedAt: '2026-04-09',
    dateModified: '2026-04-09',
    titleRu: 'Ботокс в Бельцах: что нужно знать перед процедурой | Meddera',
    titleRo: 'Botox în Bălți: ce trebuie să știți înainte de procedură | Meddera',
    descriptionRu: 'Ботокс в Бельцах: показания, противопоказания, подготовка к процедуре. Консультация в клинике Meddera.',
    descriptionRo: 'Botox în Bălți: indicații, contraindicații, pregătire pentru procedură. Consultație la clinica Meddera.',
    excerptRu: 'Всё, что нужно знать перед первой процедурой ботокса.',
    excerptRo: 'Tot ce trebuie să știți înainte de prima procedură cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-pokazaniya-protivopokazaniya',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-pokazaniya-protivopokazaniya-beltsy',
    slugRo: 'botox-indicatii-contraindicatii-balti',
    publishedAt: '2026-04-09',
    dateModified: '2026-04-09',
    titleRu: 'Ботокс: показания и противопоказания | Meddera, Бельцы',
    titleRo: 'Botox: indicații și contraindicații | Meddera, Bălți',
    descriptionRu: 'Показания и противопоказания к инъекциям ботокса. Консультация дерматокосметолога в Бельцах.',
    descriptionRo: 'Indicații și contraindicații pentru injecțiile cu botox. Consultația dermatocosmetologului în Bălți.',
    excerptRu: 'Когда показан ботокс и кому процедура противопоказана.',
    excerptRo: 'Când este indicat botoxul și cui este contraindicată procedura.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-kak-prohodit-procedura',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-kak-prohodit-procedura-etapy-beltsy',
    slugRo: 'botox-cum-decurge-procedura-etape-balti',
    publishedAt: '2026-04-09',
    dateModified: '2026-04-09',
    titleRu: 'Ботокс: как проходит процедура — этапы | Meddera',
    titleRo: 'Botox: cum decurge procedura — etape | Meddera',
    descriptionRu: 'Этапы процедуры ботокса: консультация, разметка, инъекции, рекомендации. Клиника Meddera, Бельцы.',
    descriptionRo: 'Etapele procedurii cu botox: consultație, marcare, injecții, recomandări. Clinica Meddera, Bălți.',
    excerptRu: 'Подробное описание этапов процедуры ботокса.',
    excerptRo: 'Descriere detaliată a etapelor procedurii cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-rezultaty-dlitelnost',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-rezultaty-dlitelnost-effekta-beltsy',
    slugRo: 'botox-rezultate-durata-efectului-balti',
    publishedAt: '2026-04-16',
    dateModified: '2026-04-16',
    titleRu: 'Ботокс: результаты и длительность эффекта | Meddera',
    titleRo: 'Botox: rezultate și durata efectului | Meddera',
    descriptionRu: 'Когда виден результат ботокса, сколько держится эффект. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Când este vizibil rezultatul botoxului, cât ține efectul. Consultație la Meddera, Bălți.',
    excerptRu: 'Когда ждать результат и как долго он сохраняется.',
    excerptRo: 'Când să așteptați rezultatul și cât timp se păstrează.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-uhod-posle-procedury',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-uhod-posle-procedury-rekomendacii',
    slugRo: 'botox-ingrijire-dupa-procedura-recomandari',
    publishedAt: '2026-04-16',
    dateModified: '2026-04-16',
    titleRu: 'Уход после ботокса: рекомендации | Meddera, Бельцы',
    titleRo: 'Îngrijire după botox: recomandări | Meddera, Bălți',
    descriptionRu: 'Что можно и нельзя делать после ботокса. Рекомендации дерматокосметолога Meddera.',
    descriptionRo: 'Ce se poate și nu se poate face după botox. Recomandările dermatocosmetologului Meddera.',
    excerptRu: 'Правила ухода после процедуры ботокса.',
    excerptRo: 'Reguli de îngrijire după procedura cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-zony-injekcij',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-zony-injekcij-lob-mezhbrove-beltsy',
    slugRo: 'botox-zone-injectii-frunte-intre-sprancene-balti',
    publishedAt: '2026-04-23',
    dateModified: '2026-04-23',
    titleRu: 'Зоны инъекций ботокса: лоб, межбровье | Meddera',
    titleRo: 'Zone de injecții cu botox: frunte, între sprâncene | Meddera',
    descriptionRu: 'Зоны коррекции ботоксом: лоб, межбровье, гусиные лапки. Консультация в Бельцах.',
    descriptionRo: 'Zone de corecție cu botox: frunte, între sprâncene, picioare de gâscă. Consultație în Bălți.',
    excerptRu: 'Какие зоны корректируются ботоксом.',
    excerptRo: 'Ce zone se corectează cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-oslozhneniya-pobelochnye-effekty',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-oslozhneniya-pobochnye-effekty-beltsy',
    slugRo: 'botox-complicatii-efecte-secundare-balti',
    publishedAt: '2026-04-23',
    dateModified: '2026-04-23',
    titleRu: 'Ботокс: осложнения и побочные эффекты | Meddera',
    titleRo: 'Botox: complicații și efecte secundare | Meddera',
    descriptionRu: 'Возможные осложнения после ботокса и как их избежать. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Complicații posibile după botox și cum să le evitați. Consultație la Meddera, Bălți.',
    excerptRu: 'Побочные эффекты ботокса и профилактика осложнений.',
    excerptRo: 'Efecte secundare ale botoxului și prevenirea complicațiilor.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-chastota-povtornyh-procedur',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-chastota-povtornyh-procedur-beltsy',
    slugRo: 'botox-frecventa-procedurilor-repetate-balti',
    publishedAt: '2026-04-30',
    dateModified: '2026-04-30',
    titleRu: 'Как часто можно делать ботокс | Meddera, Бельцы',
    titleRo: 'Cât de des se poate face botox | Meddera, Bălți',
    descriptionRu: 'Оптимальная частота инъекций ботокса. Консультация дерматокосметолога в Бельцах.',
    descriptionRo: 'Frecvența optimă a injecțiilor cu botox. Consultația dermatocosmetologului în Bălți.',
    excerptRu: 'Интервалы между процедурами ботокса.',
    excerptRo: 'Intervale între procedurile cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-vozrast-kogda-nachinat',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-vozrast-kogda-nachinat-beltsy',
    slugRo: 'botox-varsta-cand-sa-incepeti-balti',
    publishedAt: '2026-04-30',
    dateModified: '2026-04-30',
    titleRu: 'С какого возраста можно делать ботокс | Meddera',
    titleRo: 'De la ce vârstă se poate face botox | Meddera',
    descriptionRu: 'Оптимальный возраст для первой процедуры ботокса. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Vârsta optimă pentru prima procedură cu botox. Consultație la Meddera, Bălți.',
    excerptRu: 'Когда начинать делать ботокс: профилактика и коррекция.',
    excerptRo: 'Când să începeți să faceți botox: prevenire și corecție.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-vs-fillery-raznica',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-vs-fillery-v-chem-raznica-beltsy',
    slugRo: 'botox-vs-fillere-care-diferenta-balti',
    publishedAt: '2026-05-07',
    dateModified: '2026-05-07',
    titleRu: 'Ботокс vs филлеры: в чём разница | Meddera, Бельцы',
    titleRo: 'Botox vs fillere: care este diferența | Meddera, Bălți',
    descriptionRu: 'Разница между ботоксом и филлерами: механизм действия, зоны применения. Консультация в Бельцах.',
    descriptionRo: 'Diferența între botox și fillere: mecanism de acțiune, zone de aplicare. Consultație în Bălți.',
    excerptRu: 'Чем отличаются ботокс и филлеры.',
    excerptRo: 'Cum diferă botoxul de fillere.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-mify-pravda',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-mify-i-pravda-beltsy',
    slugRo: 'botox-mituri-si-adevar-balti',
    publishedAt: '2026-05-07',
    dateModified: '2026-05-07',
    titleRu: 'Ботокс: мифы и правда | Meddera, Бельцы',
    titleRo: 'Botox: mituri și adevăr | Meddera, Bălți',
    descriptionRu: 'Распространённые мифы о ботоксе и научные факты. Консультация дерматокосметолога в Бельцах.',
    descriptionRo: 'Mituri frecvente despre botox și fapte științifice. Consultația dermatocosmetologului în Bălți.',
    excerptRu: 'Развенчиваем популярные мифы о ботоксе.',
    excerptRo: 'Demontăm miturile populare despre botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-preparaty-vidy',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-preparaty-vidy-botulotoksina-beltsy',
    slugRo: 'botox-preparate-tipuri-toxina-botulinica-balti',
    publishedAt: '2026-05-14',
    dateModified: '2026-05-14',
    titleRu: 'Препараты ботокса: виды ботулотоксина | Meddera',
    titleRo: 'Preparate de botox: tipuri de toxină botulină | Meddera',
    descriptionRu: 'Виды препаратов ботулотоксина: Ботокс, Диспорт, Ксеомин. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Tipuri de preparate cu toxină botulină: Botox, Dysport, Xeomin. Consultație la Meddera, Bălți.',
    excerptRu: 'Какие препараты ботулотоксина используются.',
    excerptRo: 'Ce preparate cu toxină botulină se folosesc.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-gusiyne-lapki',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-gusinye-lapki-morshchiny-glaz-beltsy',
    slugRo: 'botox-picioare-gasca-riduri-ochi-balti',
    publishedAt: '2026-05-14',
    dateModified: '2026-05-14',
    titleRu: 'Ботокс от гусиных лапок | Meddera, Бельцы',
    titleRo: 'Botox pentru picioare de gâscă | Meddera, Bălți',
    descriptionRu: 'Коррекция морщин вокруг глаз ботоксом. Консультация в клинике Meddera, Бельцы.',
    descriptionRo: 'Corecția ridurilor din jurul ochilor cu botox. Consultație la clinica Meddera, Bălți.',
    excerptRu: 'Как убрать морщины вокруг глаз ботоксом.',
    excerptRo: 'Cum să eliminați ridurile din jurul ochilor cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-mezhbrove-skladka-lva',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-mezhbrove-skladka-lva-beltsy',
    slugRo: 'botox-intre-sprancene-cuta-leului-balti',
    publishedAt: '2026-05-21',
    dateModified: '2026-05-21',
    titleRu: 'Ботокс межбровья: коррекция складки льва | Meddera',
    titleRo: 'Botox între sprâncene: corecția cutei leului | Meddera',
    descriptionRu: 'Коррекция вертикальных морщин межбровья ботоксом. Консультация в Бельцах.',
    descriptionRo: 'Corecția ridurilor verticale dintre sprâncene cu botox. Consultație în Bălți.',
    excerptRu: 'Как убрать складку льва ботоксом.',
    excerptRo: 'Cum să eliminați cuta leului cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-lob-gorizontalnye-morshchiny',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-lob-gorizontalnye-morshchiny-beltsy',
    slugRo: 'botox-frunte-riduri-orizontale-balti',
    publishedAt: '2026-05-21',
    dateModified: '2026-05-21',
    titleRu: 'Ботокс лба: коррекция горизонтальных морщин | Meddera',
    titleRo: 'Botox pentru frunte: corecția ridurilor orizontale | Meddera',
    descriptionRu: 'Коррекция горизонтальных морщин лба ботоксом. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Corecția ridurilor orizontale ale frunții cu botox. Consultație la Meddera, Bălți.',
    excerptRu: 'Как разгладить морщины на лбу ботоксом.',
    excerptRo: 'Cum să netezești ridurile de pe frunte cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-brovi-lifting',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-brovi-lifting-podemka-beltsy',
    slugRo: 'botox-sprancene-lifting-ridicare-balti',
    publishedAt: '2026-05-28',
    dateModified: '2026-05-28',
    titleRu: 'Ботокс для бровей: лифтинг и подъёмка | Meddera',
    titleRo: 'Botox pentru sprâncene: lifting și ridicare | Meddera',
    descriptionRu: 'Лифтинг бровей ботоксом: открытый взгляд без операции. Консультация в Бельцах.',
    descriptionRo: 'Lifting de sprâncene cu botox: privire deschisă fără operație. Consultație în Bălți.',
    excerptRu: 'Как приподнять брови ботоксом.',
    excerptRo: 'Cum să ridicați sprâncenele cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-nos-korrekciya',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-nos-korrekciya-beltsy',
    slugRo: 'botox-nas-corectie-balti',
    publishedAt: '2026-05-28',
    dateModified: '2026-05-28',
    titleRu: 'Ботокс носа: коррекция без операции | Meddera',
    titleRo: 'Botox pentru nas: corecție fără operație | Meddera',
    descriptionRu: 'Коррекция кончика носа и морщин на переносице ботоксом. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Corecția vârfului nasului și ridurilor de pe nas cu botox. Consultație la Meddera, Bălți.',
    excerptRu: 'Как скорректировать нос ботоксом.',
    excerptRo: 'Cum să corectați nasul cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-podborodok-morshchiny',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-podborodok-morshchiny-beltsy',
    slugRo: 'botox-barbie-riduri-balti',
    publishedAt: '2026-06-04',
    dateModified: '2026-06-04',
    titleRu: 'Ботокс подбородка: коррекция морщин | Meddera',
    titleRo: 'Botox pentru bărbie: corecția ridurilor | Meddera',
    descriptionRu: 'Коррекция морщин подбородка ботоксом. Консультация в клинике Meddera, Бельцы.',
    descriptionRo: 'Corecția ridurilor bărbiei cu botox. Consultație la clinica Meddera, Bălți.',
    excerptRu: 'Как убрать морщины на подбородке ботоксом.',
    excerptRo: 'Cum să eliminați ridurile de pe bărbie cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-sheya-platizmy',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-sheya-korrekciya-platizmy-beltsy',
    slugRo: 'botox-gat-corectie-platisma-balti',
    publishedAt: '2026-06-04',
    dateModified: '2026-06-04',
    titleRu: 'Ботокс шеи: коррекция платизмы | Meddera, Бельцы',
    titleRo: 'Botox pentru gât: corecția platismei | Meddera, Bălți',
    descriptionRu: 'Коррекция тяжей шеи ботоксом. Консультация дерматокосметолога в Бельцах.',
    descriptionRo: 'Corecția cordoanelor gâtului cu botox. Consultația dermatocosmetologului în Bălți.',
    excerptRu: 'Как убрать тяжи на шее ботоксом.',
    excerptRo: 'Cum să eliminați cordoanele de pe gât cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-gipergidroz-podmyshek',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-gipergidroz-podmyshek-beltsy',
    slugRo: 'botox-hiperhidroza-axile-balti',
    publishedAt: '2026-06-11',
    dateModified: '2026-06-11',
    titleRu: 'Ботокс от гипергидроза подмышек | Meddera, Бельцы',
    titleRo: 'Botox pentru hiperhidroza axilelor | Meddera, Bălți',
    descriptionRu: 'Лечение повышенной потливости подмышек ботоксом. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Tratamentul transpirației crescute a axilelor cu botox. Consultație la Meddera, Bălți.',
    excerptRu: 'Как избавиться от потливости ботоксом.',
    excerptRo: 'Cum să scăpați de transpirație cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-bruksizm-skrezhetanie-zubami',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-bruksizm-skrezhetanie-zubami-beltsy',
    slugRo: 'botox-bruxism-scrasnit-dinti-balti',
    publishedAt: '2026-06-11',
    dateModified: '2026-06-11',
    titleRu: 'Ботокс при бруксизме: лечение скрежетания зубами | Meddera',
    titleRo: 'Botox pentru bruxism: tratamentul scrâșnitului dinților | Meddera',
    descriptionRu: 'Лечение бруксизма ботоксом: расслабление жевательных мышц. Консультация в Бельцах.',
    descriptionRo: 'Tratamentul bruxismului cu botox: relaxarea mușchilor masticatori. Consultație în Bălți.',
    excerptRu: 'Как ботокс помогает при бруксизме.',
    excerptRo: 'Cum ajută botoxul la bruxism.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-desnevaya-ulybka',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-desnevaya-ulybka-korrekciya-beltsy',
    slugRo: 'botox-zambet-gingival-corectie-balti',
    publishedAt: '2026-06-18',
    dateModified: '2026-06-18',
    titleRu: 'Ботокс при десневой улыбке: коррекция | Meddera',
    titleRo: 'Botox pentru zâmbet gingival: corecție | Meddera',
    descriptionRu: 'Коррекция десневой улыбки ботоксом. Консультация в клинике Meddera, Бельцы.',
    descriptionRo: 'Corecția zâmbetului gingival cu botox. Consultație la clinica Meddera, Bălți.',
    excerptRu: 'Как скорректировать десневую улыбку ботоксом.',
    excerptRo: 'Cum să corectați zâmbetul gingival cu botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-migreni-golovnye-boli',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-migreni-golovnye-boli-lechenie-beltsy',
    slugRo: 'botox-migrena-dureri-cap-tratament-balti',
    publishedAt: '2026-06-18',
    dateModified: '2026-06-18',
    titleRu: 'Ботокс при мигрени и головных болях | Meddera',
    titleRo: 'Botox pentru migrenă și dureri de cap | Meddera',
    descriptionRu: 'Лечение хронической мигрени ботоксом. Консультация дерматокосметолога в Бельцах.',
    descriptionRo: 'Tratamentul migrenei cronice cu botox. Consultația dermatocosmetologului în Bălți.',
    excerptRu: 'Как ботокс помогает при мигрени.',
    excerptRo: 'Cum ajută botoxul la migrenă.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-beremennost-grudnoe-vskarmlivanie',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-beremennost-grudnoe-vskarmlivanie-beltsy',
    slugRo: 'botox-sarcina-alaptare-balti',
    publishedAt: '2026-06-25',
    dateModified: '2026-06-25',
    titleRu: 'Ботокс при беременности и грудном вскармливании | Meddera',
    titleRo: 'Botox în sarcină și alăptare | Meddera',
    descriptionRu: 'Можно ли делать ботокс при беременности и ГВ. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Se poate face botox în sarcină și alăptare. Consultație la Meddera, Bălți.',
    excerptRu: 'Безопасность ботокса при беременности и ГВ.',
    excerptRo: 'Siguranța botoxului în sarcină și alăptare.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-muzhchinam-osobennosti',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-muzhchinam-osobennosti-beltsy',
    slugRo: 'botox-barbati-particularitati-balti',
    publishedAt: '2026-06-25',
    dateModified: '2026-06-25',
    titleRu: 'Ботокс для мужчин: особенности процедуры | Meddera',
    titleRo: 'Botox pentru bărbați: particularități ale procedurii | Meddera',
    descriptionRu: 'Особенности инъекций ботокса мужчинам. Консультация в клинике Meddera, Бельцы.',
    descriptionRo: 'Particularitățile injecțiilor cu botox la bărbați. Consultație la clinica Meddera, Bălți.',
    excerptRu: 'Чем отличается ботокс для мужчин.',
    excerptRo: 'Cum diferă botoxul pentru bărbați.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
];
