import type { BlogPost } from '@/blog-data/types';

/** Part 2 articles 26–50 — botox */

export const botoxArticlesPart2: BlogPost[] = [
  {
    id: 'botoks-mikrodozy-lbu',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-mikrodozy-lbu-beltsy',
    slugRo: 'botox-microdoze-frunte-balti',
    publishedAt: '2026-07-26',
    dateModified: '2026-07-26',
    titleRu: 'Ботокс лба: микродозы | Meddera',
    titleRo: 'Botox frunte: microdoze | Meddera',
    descriptionRu: 'Ботокс лба: микродозы: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox frunte: microdoze: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс лба: микродозы.',
    excerptRo: 'Pe scurt: botox frunte: microdoze.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-kombinaciya-fillery',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-kombinaciya-fillery-beltsy',
    slugRo: 'botox-combinatie-fillere-balti',
    publishedAt: '2026-07-27',
    dateModified: '2026-07-27',
    titleRu: 'Ботокс и филлеры | Meddera',
    titleRo: 'Botox și fillere | Meddera',
    descriptionRu: 'Ботокс и филлеры: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox și fillere: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс и филлеры.',
    excerptRo: 'Pe scurt: botox și fillere.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-kombinaciya-mezoterapiya',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-kombinaciya-mezoterapiya-beltsy',
    slugRo: 'botox-combinatie-mezoterapie-balti',
    publishedAt: '2026-07-28',
    dateModified: '2026-07-28',
    titleRu: 'Ботокс и мезотерапия | Meddera',
    titleRo: 'Botox și mezoterapie | Meddera',
    descriptionRu: 'Ботокс и мезотерапия: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox și mezoterapie: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс и мезотерапия.',
    excerptRo: 'Pe scurt: botox și mezoterapie.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-vnutrimyshechnaya-gipergidroz',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-vnutrimyshechnaya-gipergidroz-beltsy',
    slugRo: 'botox-hiperhidroza-palme-balti',
    publishedAt: '2026-07-29',
    dateModified: '2026-07-29',
    titleRu: 'Ботокс при гипергидрозе ладоней | Meddera',
    titleRo: 'Botox pentru hiperhidroza palmelor | Meddera',
    descriptionRu: 'Ботокс при гипергидрозе ладоней: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox pentru hiperhidroza palmelor: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс при гипергидрозе ладоней.',
    excerptRo: 'Pe scurt: botox pentru hiperhidroza palmelor.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-bruxizm-podborodok',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-bruxizm-podborodok-beltsy',
    slugRo: 'botox-bruxism-barbie-balti',
    publishedAt: '2026-07-30',
    dateModified: '2026-07-30',
    titleRu: 'Ботокс и бруксизм | Meddera',
    titleRo: 'Botox și bruxism | Meddera',
    descriptionRu: 'Ботокс и бруксизм: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox și bruxism: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс и бруксизм.',
    excerptRo: 'Pe scurt: botox și bruxism.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-gorizontalnye-morshchiny-vtoroj-plan',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-gorizontalnye-morshchiny-vtoroj-plan-beltsy',
    slugRo: 'botox-riduri-orizontale-detaliu-balti',
    publishedAt: '2026-07-31',
    dateModified: '2026-07-31',
    titleRu: 'Горизонтальные морщины лба | Meddera',
    titleRo: 'Riduri orizontale pe frunte | Meddera',
    descriptionRu: 'Горизонтальные морщины лба: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Riduri orizontale pe frunte: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: горизонтальные морщины лба.',
    excerptRo: 'Pe scurt: riduri orizontale pe frunte.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-lateralnyj-vzglyad-glaza',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-lateralnyj-vzglyad-glaza-beltsy',
    slugRo: 'botox-mimica-laterala-ochi-balti',
    publishedAt: '2026-08-01',
    dateModified: '2026-08-01',
    titleRu: 'Ботокс и зона вокруг глаз | Meddera',
    titleRo: 'Botox zona perioculară | Meddera',
    descriptionRu: 'Ботокс и зона вокруг глаз: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox zona perioculară: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс и зона вокруг глаз.',
    excerptRo: 'Pe scurt: botox zona perioculară.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-asimmetriya-mimiki',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-asimmetriya-mimiki-beltsy',
    slugRo: 'botox-asimetrie-mimica-balti',
    publishedAt: '2026-08-02',
    dateModified: '2026-08-02',
    titleRu: 'Асимметрия мимики | Meddera',
    titleRo: 'Asimetria mimică | Meddera',
    descriptionRu: 'Асимметрия мимики: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Asimetria mimică: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: асимметрия мимики.',
    excerptRo: 'Pe scurt: asimetria mimică.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-perenosica-krolik',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-perenosica-krolik-beltsy',
    slugRo: 'botox-riduri-iepure-balti',
    publishedAt: '2026-08-03',
    dateModified: '2026-08-03',
    titleRu: 'Морщины переносицы | Meddera',
    titleRo: 'Riduri pe nas | Meddera',
    descriptionRu: 'Морщины переносицы: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Riduri pe nas: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: морщины переносицы.',
    excerptRo: 'Pe scurt: riduri pe nas.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-podborodochnaya-myshca',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-podborodochnaya-myshca-beltsy',
    slugRo: 'botox-muschi-barbie-balti',
    publishedAt: '2026-08-04',
    dateModified: '2026-08-04',
    titleRu: 'Подбородочная зона | Meddera',
    titleRo: 'Zona bărbiei | Meddera',
    descriptionRu: 'Подбородочная зона: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Zona bărbiei: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: подбородочная зона.',
    excerptRo: 'Pe scurt: zona bărbiei.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-platisma-grubyj-kontur',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-platisma-grubyj-kontur-beltsy',
    slugRo: 'botox-platisma-contur-gros-balti',
    publishedAt: '2026-08-05',
    dateModified: '2026-08-05',
    titleRu: 'Платизма и контур | Meddera',
    titleRo: 'Platisma și contur | Meddera',
    descriptionRu: 'Платизма и контур: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Platisma și contur: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: платизма и контур.',
    excerptRo: 'Pe scurt: platisma și contur.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-hronicheskaya-migranya',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-hronicheskaya-migranya-beltsy',
    slugRo: 'botox-migrena-cronica-balti',
    publishedAt: '2026-08-06',
    dateModified: '2026-08-06',
    titleRu: 'Ботокс при хронической мигрени | Meddera',
    titleRo: 'Botox în migrenă cronică | Meddera',
    descriptionRu: 'Ботокс при хронической мигрени: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox în migrenă cronică: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс при хронической мигрени.',
    excerptRo: 'Pe scurt: botox în migrenă cronică.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-pobochnye-blizko-k-glazu',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-pobochnye-blizko-k-glazu-beltsy',
    slugRo: 'botox-efecte-lateral-ochi-balti',
    publishedAt: '2026-08-07',
    dateModified: '2026-08-07',
    titleRu: 'Побочные эффекты у глаз | Meddera',
    titleRo: 'Efecte laterale perioculare | Meddera',
    descriptionRu: 'Побочные эффекты у глаз: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Efecte laterale perioculare: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: побочные эффекты у глаз.',
    excerptRo: 'Pe scurt: efecte laterale perioculare.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-chrezmernaya-relaksaciya',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-chrezmernaya-relaksaciya-beltsy',
    slugRo: 'botox-relaxare-excesiva-balti',
    publishedAt: '2026-08-08',
    dateModified: '2026-08-08',
    titleRu: 'Чрезмерная релаксация | Meddera',
    titleRo: 'Relaxare excesivă | Meddera',
    descriptionRu: 'Чрезмерная релаксация: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Relaxare excesivă: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: чрезмерная релаксация.',
    excerptRo: 'Pe scurt: relaxare excesivă.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-immunitet-k-preparatu',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-immunitet-k-preparatu-beltsy',
    slugRo: 'botox-imunitate-la-preparat-balti',
    publishedAt: '2026-08-09',
    dateModified: '2026-08-09',
    titleRu: 'Резистентность к препарату | Meddera',
    titleRo: 'Rezistență la preparat | Meddera',
    descriptionRu: 'Резистентность к препарату: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Rezistență la preparat: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: резистентность к препарату.',
    excerptRo: 'Pe scurt: rezistență la preparat.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-pervyj-raz-posle-dolgogo-pereryva',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-pervyj-raz-posle-dolgogo-pereryva-beltsy',
    slugRo: 'botox-prima-data-dupa-pauza-balti',
    publishedAt: '2026-08-10',
    dateModified: '2026-08-10',
    titleRu: 'Первый раз после паузы | Meddera',
    titleRo: 'Prima procedură după pauză | Meddera',
    descriptionRu: 'Первый раз после паузы: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Prima procedură după pauză: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: первый раз после паузы.',
    excerptRo: 'Pe scurt: prima procedură după pauză.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-muzhskoj-licevoj-tip',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-muzhskoj-licevoj-tip-beltsy',
    slugRo: 'botox-tip-fata-barbati-balti',
    publishedAt: '2026-08-11',
    dateModified: '2026-08-11',
    titleRu: 'Ботокс для мужчин | Meddera',
    titleRo: 'Botox la bărbați | Meddera',
    descriptionRu: 'Ботокс для мужчин: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox la bărbați: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс для мужчин.',
    excerptRo: 'Pe scurt: botox la bărbați.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-zhenschina-40-plus',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-zhenschina-40-plus-beltsy',
    slugRo: 'botox-femei-peste-40-balti',
    publishedAt: '2026-08-12',
    dateModified: '2026-08-12',
    titleRu: 'Ботокс после 40 | Meddera',
    titleRo: 'Botox după 40 de ani | Meddera',
    descriptionRu: 'Ботокс после 40: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox după 40 de ani: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс после 40.',
    excerptRo: 'Pe scurt: botox după 40 de ani.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-zhenschina-55-plus',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-zhenschina-55-plus-beltsy',
    slugRo: 'botox-femei-peste-55-balti',
    publishedAt: '2026-08-13',
    dateModified: '2026-08-13',
    titleRu: 'Ботокс после 55 | Meddera',
    titleRo: 'Botox după 55 de ani | Meddera',
    descriptionRu: 'Ботокс после 55: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox după 55 de ani: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс после 55.',
    excerptRo: 'Pe scurt: botox după 55 de ani.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-professionalnaya-mimika',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-professionalnaya-mimika-beltsy',
    slugRo: 'botox-mimica-profesionala-balti',
    publishedAt: '2026-08-14',
    dateModified: '2026-08-14',
    titleRu: 'Мимика и профессия | Meddera',
    titleRo: 'Mimica și profesie | Meddera',
    descriptionRu: 'Мимика и профессия: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Mimica și profesie: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: мимика и профессия.',
    excerptRo: 'Pe scurt: mimica și profesie.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-pered-vazhnoj-datoj',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-pered-vazhnoj-datoj-beltsy',
    slugRo: 'botox-inainte-eveniment-balti',
    publishedAt: '2026-08-15',
    dateModified: '2026-08-15',
    titleRu: 'Ботокс перед мероприятием | Meddera',
    titleRo: 'Botox înainte de eveniment | Meddera',
    descriptionRu: 'Ботокс перед мероприятием: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox înainte de eveniment: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс перед мероприятием.',
    excerptRo: 'Pe scurt: botox înainte de eveniment.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-posle-bolezni-perenos',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-posle-bolezni-perenos-beltsy',
    slugRo: 'botox-dupa-boala-amanare-balti',
    publishedAt: '2026-08-16',
    dateModified: '2026-08-16',
    titleRu: 'Ботокс после перенесённой болезни | Meddera',
    titleRo: 'Botox după boală | Meddera',
    descriptionRu: 'Ботокс после перенесённой болезни: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox după boală: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс после перенесённой болезни.',
    excerptRo: 'Pe scurt: botox după boală.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-i-antikoagulyanty',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-i-antikoagulyanty-beltsy',
    slugRo: 'botox-si-anticoagulante-balti',
    publishedAt: '2026-08-17',
    dateModified: '2026-08-17',
    titleRu: 'Ботокс и антикоагулянты | Meddera',
    titleRo: 'Botox și anticoagulante | Meddera',
    descriptionRu: 'Ботокс и антикоагулянты: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox și anticoagulante: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс и антикоагулянты.',
    excerptRo: 'Pe scurt: botox și anticoagulante.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-i-antibiotiki',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-i-antibiotiki-beltsy',
    slugRo: 'botox-si-antibiotice-balti',
    publishedAt: '2026-08-18',
    dateModified: '2026-08-18',
    titleRu: 'Ботокс и антибиотики | Meddera',
    titleRo: 'Botox și antibiotice | Meddera',
    descriptionRu: 'Ботокс и антибиотики: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Botox și antibiotice: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ботокс и антибиотики.',
    excerptRo: 'Pe scurt: botox și antibiotice.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'botoks-zapis-konsultaciya',
    kind: 'article',
    clusterId: 'botox',
    slugRu: 'botoks-zapis-konsultaciya-beltsy',
    slugRo: 'botox-programare-consultatie-balti',
    publishedAt: '2026-08-19',
    dateModified: '2026-08-19',
    titleRu: 'Запись на консультацию по ботоксу | Meddera',
    titleRo: 'Programare consultație botox | Meddera',
    descriptionRu: 'Запись на консультацию по ботоксу: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Programare consultație botox: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: запись на консультацию по ботоксу.',
    excerptRo: 'Pe scurt: programare consultație botox.',
    bodyKey: 'botox-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
];
