import type { BlogPost } from '@/blog-data/types';

/**
 * Рубрика "Дерматолог в Бельцах" — часть 1 (статьи 1-25)
 * Контент: 800-1500 слов, 4-6 секций H2, 5-8 internal links
 */

export const dermatologistArticlesPart1: BlogPost[] = [
  {
    id: 'dermatolog-beltsy-kogda-nuzhna-konsultaciya',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'dermatolog-beltsy-kogda-nuzhna-konsultaciya',
    slugRo: 'dermatolog-balti-cand-este-necesara-consultatie',
    publishedAt: '2026-04-08',
    dateModified: '2026-04-08',
    titleRu: 'Дерматолог в Бельцах: когда нужна консультация | Meddera',
    titleRo: 'Dermatolog în Bălți: când este necesară consultația | Meddera',
    descriptionRu: 'Когда обращаться к дерматологу в Бельцах: симптомы, показания, подготовка к приёму. Консультация в клинике Meddera.',
    descriptionRo: 'Când să consultați dermatologul în Bălți: simptome, indicații, pregătire pentru vizită. Consultație la clinica Meddera.',
    excerptRu: 'Симптомы и ситуации, когда необходима консультация дерматолога.',
    excerptRo: 'Simptome și situații când este necesară consultația dermatologului.',
    bodyKey: 'dermatologist-article',
    authorByline: {
      ru: 'Meddera Beauty Clinic',
      ro: 'Meddera Beauty Clinic',
    },
    medicalReview: {
      ru: 'Материал подготовлен специалистами клиники Meddera, Бельцы. Информация носит ознакомительный характер и не заменяет очную консультацию с врачом-дерматологом.',
      ro: 'Materialul a fost pregătit de specialiștii clinicii Meddera, Bălți. Informația are caracter informativ și nu înlocuiește consultația cu medicul dermatolog.',
    },
  },
  {
    id: 'akne-prichiny-stadii-lechenie',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'akne-prichiny-stadii-lechenie-beltsy',
    slugRo: 'acnee-cauze-stadii-tratament-balti',
    publishedAt: '2026-04-08',
    dateModified: '2026-04-08',
    titleRu: 'Акне: причины, стадии и методы лечения в Бельцах | Meddera',
    titleRo: 'Acnee: cauze, stadii și metode de tratament în Bălți | Meddera',
    descriptionRu: 'Акне (угревая болезнь): причины, стадии, современные методы лечения. Консультация дерматолога в Meddera, Бельцы.',
    descriptionRo: 'Acnee (boala acneică): cauze, stadii, metode moderne de tratament. Consultația dermatologului la Meddera, Bălți.',
    excerptRu: 'Комплексный подход к лечению акне: от диагностики до результата.',
    excerptRo: 'Abordare complexă în tratamentul acneei: de la diagnostic la rezultat.',
    bodyKey: 'dermatologist-article',
    authorByline: {
      ru: 'Meddera Beauty Clinic',
      ro: 'Meddera Beauty Clinic',
    },
  },
  {
    id: 'psoriaz-sovremennye-podhody-terapii',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'psoriaz-sovremennye-podhody-terapii-beltsy',
    slugRo: 'psoriazis-abordari-moderne-tratament-balti',
    publishedAt: '2026-04-08',
    dateModified: '2026-04-08',
    titleRu: 'Псориаз: современные подходы к терапии в Бельцах | Meddera',
    titleRo: 'Psoriazis: abordări moderne în tratament în Bălți | Meddera',
    descriptionRu: 'Псориаз: диагностика, современные методы лечения, контроль обострений. Консультация дерматолога в Meddera.',
    descriptionRo: 'Psoriazis: diagnostic, metode moderne de tratament, controlul exacerbărilor. Consultația dermatologului la Meddera.',
    excerptRu: 'Как современная дерматология помогает контролировать псориаз.',
    excerptRo: 'Cum ajută dermatologia modernă să controlați psoriazisul.',
    bodyKey: 'dermatologist-article',
    authorByline: {
      ru: 'Meddera Beauty Clinic',
      ro: 'Meddera Beauty Clinic',
    },
  },
  {
    id: 'ekzema-kak-oblegchit-simptomy',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'ekzema-kak-oblegchit-simptomy-beltsy',
    slugRo: 'eczema-cum-sa-ameliorati-simptomele-balti',
    publishedAt: '2026-04-08',
    dateModified: '2026-04-08',
    titleRu: 'Экзема: как облегчить симптомы и предотвратить обострения | Meddera',
    titleRo: 'Eczemă: cum să ameliorați simptomele și să preveniți exacerbările | Meddera',
    descriptionRu: 'Экзема: причины, симптомы, лечение и профилактика обострений. Консультация дерматолога в Бельцах.',
    descriptionRo: 'Eczemă: cauze, simptome, tratament și prevenirea exacerbărilor. Consultația dermatologului în Bălți.',
    excerptRu: 'Методы облегчения симптомов экземы и профилактика рецидивов.',
    excerptRo: 'Metode de ameliorare a simptomelor eczemei și prevenirea recidivelor.',
    bodyKey: 'dermatologist-article',
    authorByline: {
      ru: 'Meddera Beauty Clinic',
      ro: 'Meddera Beauty Clinic',
    },
  },
  {
    id: 'dermatoskopiya-chto-eto-zachem-nuzhna',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'dermatoskopiya-chto-eto-zachem-nuzhna-beltsy',
    slugRo: 'dermatoscopie-ce-este-de-ce-este-necesara-balti',
    publishedAt: '2026-04-08',
    dateModified: '2026-04-08',
    titleRu: 'Дерматоскопия: что это и зачем нужна | Meddera, Бельцы',
    titleRo: 'Dermatoscopie: ce este și de ce este necesară | Meddera, Bălți',
    descriptionRu: 'Дерматоскопия в Бельцах: безболезненное исследование родинок и новообразований кожи. Клиника Meddera.',
    descriptionRo: 'Dermatoscopie în Bălți: investigație nedureroasă a aluniţelor și neoplasmelor cutanate. Clinica Meddera.',
    excerptRu: 'Как дерматоскопия помогает в ранней диагностике заболеваний кожи.',
    excerptRo: 'Cum ajută dermatoscopia în diagnosticul precoce al afecțiunilor pielii.',
    bodyKey: 'dermatologist-article',
    authorByline: {
      ru: 'Meddera Beauty Clinic',
      ro: 'Meddera Beauty Clinic',
    },
  },
  {
    id: 'rodinki-kogda-obratitsya-k-dermatologu',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'rodinki-kogda-obratitsya-k-dermatologu-beltsy',
    slugRo: 'alunite-cand-sa-consultati-dermatologul-balti',
    publishedAt: '2026-04-15',
    dateModified: '2026-04-15',
    titleRu: 'Родинки: когда стоит обратиться к дерматологу | Meddera',
    titleRo: 'Alunițe: când trebuie să consultați dermatologul | Meddera',
    descriptionRu: 'Родинки: признаки опасных изменений, когда нужен осмотр дерматолога. Дерматоскопия в Бельцах.',
    descriptionRo: 'Alunițe: semne de modificări periculoase, când este necesar examenul dermatologului. Dermatoscopie în Bălți.',
    excerptRu: 'Тревожные признаки изменений родинок и важность регулярных осмотров.',
    excerptRo: 'Semne alarmante de modificări ale aluniţelor și importanța examinărilor regulate.',
    bodyKey: 'dermatologist-article',
    authorByline: {
      ru: 'Meddera Beauty Clinic',
      ro: 'Meddera Beauty Clinic',
    },
  },
  {
    id: 'gribkovye-infekcii-kozhi-diagnostika-lechenie',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'gribkovye-infekcii-kozhi-diagnostika-lechenie-beltsy',
    slugRo: 'infectii-fungice-piele-diagnostic-tratament-balti',
    publishedAt: '2026-04-15',
    dateModified: '2026-04-15',
    titleRu: 'Грибковые инфекции кожи: диагностика и лечение | Meddera',
    titleRo: 'Infecții fungice ale pielii: diagnostic și tratament | Meddera',
    descriptionRu: 'Грибковые инфекции кожи (микозы): симптомы, диагностика, лечение. Консультация дерматолога в Бельцах.',
    descriptionRo: 'Infecții fungice ale pielii (micoze): simptome, diagnostic, tratament. Consultația dermatologului în Bălți.',
    excerptRu: 'Как распознать и эффективно лечить грибковые инфекции кожи.',
    excerptRo: 'Cum să recunoașteți și să tratați eficient infecțiile fungice ale pielii.',
    bodyKey: 'dermatologist-article',
    authorByline: {
      ru: 'Meddera Beauty Clinic',
      ro: 'Meddera Beauty Clinic',
    },
  },
  {
    id: 'rozacea-prichiny-metody-korrekcii',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'rozacea-prichiny-metody-korrekcii-beltsy',
    slugRo: 'rozacee-cauze-metode-corectie-balti',
    publishedAt: '2026-04-15',
    dateModified: '2026-04-15',
    titleRu: 'Розацеа: причины и методы коррекции в Бельцах | Meddera',
    titleRo: 'Rozacee: cauze și metode de corecție în Bălți | Meddera',
    descriptionRu: 'Розацеа: причины покраснения кожи, современные методы лечения. Консультация дерматолога в Meddera.',
    descriptionRo: 'Rozacee: cauze ale roșeții pielii, metode moderne de tratament. Consultația dermatologului la Meddera.',
    excerptRu: 'Как контролировать розацеа и улучшить состояние кожи.',
    excerptRo: 'Cum să controlați rozaceea și să îmbunătățiți starea pielii.',
    bodyKey: 'dermatologist-article',
    authorByline: {
      ru: 'Meddera Beauty Clinic',
      ro: 'Meddera Beauty Clinic',
    },
  },
  {
    id: 'atopicheskij-dermatit-uhod-profilaktika',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'atopicheskij-dermatit-uhod-profilaktika-beltsy',
    slugRo: 'dermatita-atopica-ingrijire-prevenire-balti',
    publishedAt: '2026-04-15',
    dateModified: '2026-04-15',
    titleRu: 'Атопический дерматит: уход и профилактика обострений | Meddera',
    titleRo: 'Dermatita atopică: îngrijire și prevenirea exacerbărilor | Meddera',
    descriptionRu: 'Атопический дерматит: правильный уход за кожей, профилактика обострений. Консультация дерматолога в Бельцах.',
    descriptionRo: 'Dermatita atopică: îngrijirea corectă a pielii, prevenirea exacerbărilor. Consultația dermatologului în Bălți.',
    excerptRu: 'Как ухаживать за кожей при атопическом дерматите и предотвратить обострения.',
    excerptRo: 'Cum să îngrijiți pielea în cazul dermatitei atopice și să preveniți exacerbările.',
    bodyKey: 'dermatologist-article',
    authorByline: {
      ru: 'Meddera Beauty Clinic',
      ro: 'Meddera Beauty Clinic',
    },
  },
  {
    id: 'seboreynyj-dermatit-prichiny-lechenie',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'seboreynyj-dermatit-prichiny-lechenie-beltsy',
    slugRo: 'dermatita-seboreica-cauze-tratament-balti',
    publishedAt: '2026-04-15',
    dateModified: '2026-04-15',
    titleRu: 'Себорейный дерматит: причины и лечение | Meddera, Бельцы',
    titleRo: 'Dermatita seboreică: cauze și tratament | Meddera, Bălți',
    descriptionRu: 'Себорейный дерматит: причины, симптомы, современные методы лечения. Консультация дерматолога в Meddera.',
    descriptionRo: 'Dermatita seboreică: cauze, simptome, metode moderne de tratament. Consultația dermatologului la Meddera.',
    excerptRu: 'Как эффективно лечить себорейный дерматит и контролировать симптомы.',
    excerptRo: 'Cum să tratați eficient dermatita seboreică și să controlați simptomele.',
    bodyKey: 'dermatologist-article',
    authorByline: {
      ru: 'Meddera Beauty Clinic',
      ro: 'Meddera Beauty Clinic',
    },
  },
  // Статьи 11-25 (метаданные без полного контента для демонстрации структуры)
  {
    id: 'kontaktnyj-dermatit-allergiya-razdrazhenie',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'kontaktnyj-dermatit-allergiya-razdrazhenie-beltsy',
    slugRo: 'dermatita-contact-alergie-iritatie-balti',
    publishedAt: '2026-04-22',
    dateModified: '2026-04-22',
    titleRu: 'Контактный дерматит: аллергия или раздражение | Meddera',
    titleRo: 'Dermatita de contact: alergie sau iritație | Meddera',
    descriptionRu: 'Контактный дерматит: как отличить аллергическую реакцию от раздражения, лечение. Дерматолог в Бельцах.',
    descriptionRo: 'Dermatita de contact: cum să distingeți reacția alergică de iritație, tratament. Dermatolog în Bălți.',
    excerptRu: 'Различия между аллергическим и раздражающим контактным дерматитом.',
    excerptRo: 'Diferențe între dermatita de contact alergică și iritativă.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'vitiligo-chto-eto-mozhno-li-lechit',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'vitiligo-chto-eto-mozhno-li-lechit-beltsy',
    slugRo: 'vitiligo-ce-este-se-poate-trata-balti',
    publishedAt: '2026-04-22',
    dateModified: '2026-04-22',
    titleRu: 'Витилиго: что это и можно ли лечить | Meddera, Бельцы',
    titleRo: 'Vitiligo: ce este și se poate trata | Meddera, Bălți',
    descriptionRu: 'Витилиго: причины депигментации кожи, современные методы лечения. Консультация дерматолога в Meddera.',
    descriptionRo: 'Vitiligo: cauze ale depigmentării pielii, metode moderne de tratament. Consultația dermatologului la Meddera.',
    excerptRu: 'Современные подходы к лечению витилиго и контролю депигментации.',
    excerptRo: 'Abordări moderne în tratamentul vitiligo și controlul depigmentării.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'papillomy-borodavki-udalenie-beltsy',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'papillomy-borodavki-udalenie-beltsy',
    slugRo: 'papiloame-negi-indepartare-balti',
    publishedAt: '2026-04-22',
    dateModified: '2026-04-22',
    titleRu: 'Папилломы и бородавки: удаление в Бельцах | Meddera',
    titleRo: 'Papiloame și negi: îndepărtare în Bălți | Meddera',
    descriptionRu: 'Папилломы и бородавки: причины появления, методы удаления. Консультация дерматолога в Meddera.',
    descriptionRo: 'Papiloame și negi: cauze ale apariției, metode de îndepărtare. Consultația dermatologului la Meddera.',
    excerptRu: 'Безопасное удаление папиллом и бородавок в клинике Meddera.',
    excerptRo: 'Îndepărtarea sigură a papiloamelor și negilor la clinica Meddera.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'keratomy-chto-eto-nuzhno-li-udalyat',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'keratomy-chto-eto-nuzhno-li-udalyat-beltsy',
    slugRo: 'keratoame-ce-sunt-trebuie-indepartate-balti',
    publishedAt: '2026-04-22',
    dateModified: '2026-04-22',
    titleRu: 'Кератомы: что это и нужно ли удалять | Meddera, Бельцы',
    titleRo: 'Keratoame: ce sunt și trebuie îndepărtate | Meddera, Bălți',
    descriptionRu: 'Кератомы: виды, причины появления, показания к удалению. Консультация дерматолога в Бельцах.',
    descriptionRo: 'Keratoame: tipuri, cauze ale apariției, indicații pentru îndepărtare. Consultația dermatologului în Bălți.',
    excerptRu: 'Когда кератомы требуют удаления и как это делается.',
    excerptRo: 'Când keratoamele necesită îndepărtare și cum se realizează.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'alopeciya-vypadenie-volos-prichiny',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'alopeciya-vypadenie-volos-prichiny-beltsy',
    slugRo: 'alopecie-caderea-parului-cauze-balti',
    publishedAt: '2026-04-22',
    dateModified: '2026-04-22',
    titleRu: 'Алопеция: причины выпадения волос и методы лечения | Meddera',
    titleRo: 'Alopecie: cauze ale căderii părului și metode de tratament | Meddera',
    descriptionRu: 'Алопеция: виды, причины выпадения волос, современные методы лечения. Дерматолог в Бельцах.',
    descriptionRo: 'Alopecie: tipuri, cauze ale căderii părului, metode moderne de tratament. Dermatolog în Bălți.',
    excerptRu: 'Диагностика и лечение различных видов алопеции.',
    excerptRo: 'Diagnosticul și tratamentul diferitelor tipuri de alopecie.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'seboreya-kozhi-golovy-lechenie',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'seboreya-kozhi-golovy-lechenie-beltsy',
    slugRo: 'seboreea-scalpului-tratament-balti',
    publishedAt: '2026-04-29',
    dateModified: '2026-04-29',
    titleRu: 'Себорея кожи головы: лечение и профилактика | Meddera',
    titleRo: 'Seboreea scalpului: tratament și prevenire | Meddera',
    descriptionRu: 'Себорея кожи головы: причины, симптомы, лечение. Консультация дерматолога в Бельцах.',
    descriptionRo: 'Seboreea scalpului: cauze, simptome, tratament. Consultația dermatologului în Bălți.',
    excerptRu: 'Как избавиться от себореи и предотвратить её возвращение.',
    excerptRo: 'Cum să scăpați de seboree și să preveniți reapariția acesteia.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'onikhomikoz-gribok-nogtej-lechenie',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'onikhomikoz-gribok-nogtej-lechenie-beltsy',
    slugRo: 'onicomicoza-ciuperca-unghiilor-tratament-balti',
    publishedAt: '2026-04-29',
    dateModified: '2026-04-29',
    titleRu: 'Онихомикоз: лечение грибка ногтей в Бельцах | Meddera',
    titleRo: 'Onicomicoza: tratamentul ciupercii unghiilor în Bălți | Meddera',
    descriptionRu: 'Онихомикоз (грибок ногтей): диагностика, современные методы лечения. Дерматолог в Meddera.',
    descriptionRo: 'Onicomicoza (ciuperca unghiilor): diagnostic, metode moderne de tratament. Dermatolog la Meddera.',
    excerptRu: 'Эффективное лечение грибка ногтей: системная и местная терапия.',
    excerptRo: 'Tratament eficient al ciupercii unghiilor: terapie sistemică și locală.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'vrosshij-nogot-prichiny-lechenie',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'vrosshij-nogot-prichiny-lechenie-beltsy',
    slugRo: 'unghie-incarcata-cauze-tratament-balti',
    publishedAt: '2026-04-29',
    dateModified: '2026-04-29',
    titleRu: 'Вросший ноготь: причины и лечение | Meddera, Бельцы',
    titleRo: 'Unghie încarnată: cauze și tratament | Meddera, Bălți',
    descriptionRu: 'Вросший ноготь: причины, симптомы, методы лечения. Консультация дерматолога в Бельцах.',
    descriptionRo: 'Unghie încarnată: cauze, simptome, metode de tratament. Consultația dermatologului în Bălți.',
    excerptRu: 'Как избавиться от вросшего ногтя и предотвратить рецидив.',
    excerptRo: 'Cum să scăpați de unghia încarnată și să preveniți recidiva.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'gipergidroz-lechenie-beltsy',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'gipergidroz-lechenie-povyshennoj-potlivosti-beltsy',
    slugRo: 'hiperhidroza-tratament-transpiratie-excesiva-balti',
    publishedAt: '2026-04-29',
    dateModified: '2026-04-29',
    titleRu: 'Гипергидроз: лечение повышенной потливости | Meddera',
    titleRo: 'Hiperhidroza: tratamentul transpirației excesive | Meddera',
    descriptionRu: 'Гипергидроз (повышенная потливость): причины, методы лечения. Консультация дерматолога в Бельцах.',
    descriptionRo: 'Hiperhidroza (transpirație excesivă): cauze, metode de tratament. Consultația dermatologului în Bălți.',
    excerptRu: 'Современные методы лечения гипергидроза: от местной терапии до инъекций ботокса.',
    excerptRo: 'Metode moderne de tratament al hiperhidrozei: de la terapia locală la injecțiile cu botox.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'follikulit-vospalenie-volosyanyh-follikulov',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'follikulit-vospalenie-volosyanyh-follikulov-beltsy',
    slugRo: 'foliculita-inflamatia-foliculilor-pilosi-balti',
    publishedAt: '2026-04-29',
    dateModified: '2026-04-29',
    titleRu: 'Фолликулит: воспаление волосяных фолликулов | Meddera',
    titleRo: 'Foliculita: inflamația foliculilor piloși | Meddera',
    descriptionRu: 'Фолликулит: причины, симптомы, лечение. Консультация дерматолога в Бельцах.',
    descriptionRo: 'Foliculita: cauze, simptome, tratament. Consultația dermatologului în Bălți.',
    excerptRu: 'Как лечить фолликулит и предотвратить его повторное появление.',
    excerptRo: 'Cum să tratați foliculita și să preveniți reapariția acesteia.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'impetigo-bakterialnaya-infekciya-kozhi',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'impetigo-bakterialnaya-infekciya-kozhi-beltsy',
    slugRo: 'impetigo-infectie-bacteriana-piele-balti',
    publishedAt: '2026-05-06',
    dateModified: '2026-05-06',
    titleRu: 'Импетиго: бактериальная инфекция кожи | Meddera, Бельцы',
    titleRo: 'Impetigo: infecție bacteriană a pielii | Meddera, Bălți',
    descriptionRu: 'Импетиго: симптомы, диагностика, лечение. Консультация дерматолога в Meddera.',
    descriptionRo: 'Impetigo: simptome, diagnostic, tratament. Consultația dermatologului la Meddera.',
    excerptRu: 'Быстрое и эффективное лечение импетиго у детей и взрослых.',
    excerptRo: 'Tratament rapid și eficient al impetigoului la copii și adulți.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'krapivnica-prichiny-lechenie',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'krapivnica-prichiny-lechenie-beltsy',
    slugRo: 'urticarie-cauze-tratament-balti',
    publishedAt: '2026-05-06',
    dateModified: '2026-05-06',
    titleRu: 'Крапивница: причины и лечение | Meddera, Бельцы',
    titleRo: 'Urticarie: cauze și tratament | Meddera, Bălți',
    descriptionRu: 'Крапивница: причины, симптомы, лечение. Консультация дерматолога в Бельцах.',
    descriptionRo: 'Urticarie: cauze, simptome, tratament. Consultația dermatologului în Bălți.',
    excerptRu: 'Как быстро снять симптомы крапивницы и найти причину.',
    excerptRo: 'Cum să ameliorați rapid simptomele urticariei și să găsiți cauza.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'pigmentnye-pyatna-prichiny-lechenie',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'pigmentnye-pyatna-prichiny-lechenie-beltsy',
    slugRo: 'pete-pigmentare-cauze-tratament-balti',
    publishedAt: '2026-05-06',
    dateModified: '2026-05-06',
    titleRu: 'Пигментные пятна: причины и методы лечения | Meddera',
    titleRo: 'Pete pigmentare: cauze și metode de tratament | Meddera',
    descriptionRu: 'Пигментные пятна: причины появления, современные методы лечения. Дерматолог в Бельцах.',
    descriptionRo: 'Pete pigmentare: cauze ale apariției, metode moderne de tratament. Dermatolog în Bălți.',
    excerptRu: 'Как избавиться от пигментных пятен и предотвратить их появление.',
    excerptRo: 'Cum să scăpați de petele pigmentare și să preveniți apariția lor.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fotostareenie-kozhi-profilaktika',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'fotostareenie-kozhi-profilaktika-beltsy',
    slugRo: 'fotoimbatranire-piele-prevenire-balti',
    publishedAt: '2026-05-06',
    dateModified: '2026-05-06',
    titleRu: 'Фотостарение кожи: профилактика и лечение | Meddera',
    titleRo: 'Fotoîmbătrânirea pielii: prevenire și tratament | Meddera',
    descriptionRu: 'Фотостарение: как солнце влияет на кожу, методы профилактики и лечения. Дерматолог в Бельцах.',
    descriptionRo: 'Fotoîmbătrânire: cum afectează soarele pielea, metode de prevenire și tratament. Dermatolog în Bălți.',
    excerptRu: 'Защита кожи от фотостарения и коррекция уже появившихся изменений.',
    excerptRo: 'Protecția pielii de fotoîmbătrânire și corecția modificărilor deja apărute.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'solnechnye-ozhogi-pervaya-pomoshch',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'solnechnye-ozhogi-pervaya-pomoshch-beltsy',
    slugRo: 'arsuri-solare-prim-ajutor-balti',
    publishedAt: '2026-05-06',
    dateModified: '2026-05-06',
    titleRu: 'Солнечные ожоги: первая помощь и лечение | Meddera',
    titleRo: 'Arsuri solare: prim ajutor și tratament | Meddera',
    descriptionRu: 'Солнечные ожоги: первая помощь, лечение, профилактика. Консультация дерматолога в Бельцах.',
    descriptionRo: 'Arsuri solare: prim ajutor, tratament, prevenire. Consultația dermatologului în Bălți.',
    excerptRu: 'Что делать при солнечном ожоге и как защитить кожу от повторных повреждений.',
    excerptRo: 'Ce să faceți în caz de arsură solară și cum să protejați pielea de leziuni repetate.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
];
