import type { BlogPost } from '@/blog-data/types';

/** Part 2 articles 26–50 — dermatologist */

export const dermatologistArticlesPart2: BlogPost[] = [
  {
    id: 'melanoma-rannyaya-diagnostika',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'melanoma-rannyaya-diagnostika-beltsy',
    slugRo: 'melanom-diagnostic-precoce-balti',
    publishedAt: '2026-07-01',
    dateModified: '2026-07-01',
    titleRu: 'Меланома и ранняя диагностика | Meddera',
    titleRo: 'Melanom și diagnostic precoce | Meddera',
    descriptionRu: 'Меланома и ранняя диагностика: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Melanom și diagnostic precoce: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: меланома и ранняя диагностика.',
    excerptRo: 'Pe scurt: melanom și diagnostic precoce.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'bazalioma-lechenie-udalenie',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'bazalioma-lechenie-udalenie-beltsy',
    slugRo: 'baziom-tratament-indepartare-balti',
    publishedAt: '2026-07-02',
    dateModified: '2026-07-02',
    titleRu: 'Базалиома: лечение | Meddera',
    titleRo: 'Baziom: tratament | Meddera',
    descriptionRu: 'Базалиома: лечение: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Baziom: tratament: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: базалиома: лечение.',
    excerptRo: 'Pe scurt: baziom: tratament.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'ploskokletochnyj-rak-kozhi',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'ploskokletochnyj-rak-kozhi-beltsy',
    slugRo: 'carcinom-scuamos-piele-balti',
    publishedAt: '2026-07-03',
    dateModified: '2026-07-03',
    titleRu: 'Плоскоклеточный рак кожи | Meddera',
    titleRo: 'Carcinom scuamos al pielii | Meddera',
    descriptionRu: 'Плоскоклеточный рак кожи: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Carcinom scuamos al pielii: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: плоскоклеточный рак кожи.',
    excerptRo: 'Pe scurt: carcinom scuamos al pielii.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'detskij-atopicheskij-dermatit',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'detskij-atopicheskij-dermatit-beltsy',
    slugRo: 'dermatita-atopica-copii-balti',
    publishedAt: '2026-07-04',
    dateModified: '2026-07-04',
    titleRu: 'Атопический дерматит у детей | Meddera',
    titleRo: 'Dermatita atopică la copii | Meddera',
    descriptionRu: 'Атопический дерматит у детей: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Dermatita atopică la copii: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: атопический дерматит у детей.',
    excerptRo: 'Pe scurt: dermatita atopică la copii.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'detskij-kontaktnyj-dermatit',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'detskij-kontaktnyj-dermatit-beltsy',
    slugRo: 'dermatita-contact-copii-balti',
    publishedAt: '2026-07-05',
    dateModified: '2026-07-05',
    titleRu: 'Контактный дерматит у детей | Meddera',
    titleRo: 'Dermatita de contact la copii | Meddera',
    descriptionRu: 'Контактный дерматит у детей: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Dermatita de contact la copii: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: контактный дерматит у детей.',
    excerptRo: 'Pe scurt: dermatita de contact la copii.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'podrostkovoe-akne-protokol',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'podrostkovoe-akne-protokol-beltsy',
    slugRo: 'acnee-adolescenti-protocol-balti',
    publishedAt: '2026-07-06',
    dateModified: '2026-07-06',
    titleRu: 'Подростковое акне | Meddera',
    titleRo: 'Acnee la adolescenți | Meddera',
    descriptionRu: 'Подростковое акне: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Acnee la adolescenți: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: подростковое акне.',
    excerptRo: 'Pe scurt: acnee la adolescenți.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'kosmeticheskaya-oczenka-rodinok',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'kosmeticheskaya-oczenka-rodinok-beltsy',
    slugRo: 'evaluare-alunite-consult-cosmetic-balti',
    publishedAt: '2026-07-07',
    dateModified: '2026-07-07',
    titleRu: 'Оценка родинок перед процедурами | Meddera',
    titleRo: 'Evaluarea alunițelor înainte de proceduri | Meddera',
    descriptionRu: 'Оценка родинок перед процедурами: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Evaluarea alunițelor înainte de proceduri: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: оценка родинок перед процедурами.',
    excerptRo: 'Pe scurt: evaluarea alunițelor înainte de proceduri.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'piling-licza-podgotovka',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'piling-licza-podgotovka-beltsy',
    slugRo: 'pregatire-piele-peeling-fata-balti',
    publishedAt: '2026-07-08',
    dateModified: '2026-07-08',
    titleRu: 'Пилинг: подготовка кожи | Meddera',
    titleRo: 'Peeling: pregătirea pielii | Meddera',
    descriptionRu: 'Пилинг: подготовка кожи: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Peeling: pregătirea pielii: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: пилинг: подготовка кожи.',
    excerptRo: 'Pe scurt: peeling: pregătirea pielii.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'lazer-podgotovka-kozhi',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'lazer-podgotovka-kozhi-beltsy',
    slugRo: 'pregatire-piele-proceduri-laser-balti',
    publishedAt: '2026-07-09',
    dateModified: '2026-07-09',
    titleRu: 'Лазер: подготовка | Meddera',
    titleRo: 'Laser: pregătire | Meddera',
    descriptionRu: 'Лазер: подготовка: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Laser: pregătire: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: лазер: подготовка.',
    excerptRo: 'Pe scurt: laser: pregătire.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uhod-kozha-posle-40',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'uhod-kozha-posle-40-beltsy',
    slugRo: 'ingrijire-piele-dupa-40-ani-balti',
    publishedAt: '2026-07-10',
    dateModified: '2026-07-10',
    titleRu: 'Уход за кожей после 40 лет | Meddera',
    titleRo: 'Îngrijirea pielii după 40 de ani | Meddera',
    descriptionRu: 'Уход за кожей после 40 лет: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Îngrijirea pielii după 40 de ani: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: уход за кожей после 40 лет.',
    excerptRo: 'Pe scurt: îngrijirea pielii după 40 de ani.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'suhaya-kozha-zima',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'suhaya-kozha-zima-beltsy',
    slugRo: 'piele-uscata-iarna-balti',
    publishedAt: '2026-07-11',
    dateModified: '2026-07-11',
    titleRu: 'Сухая кожа зимой | Meddera',
    titleRo: 'Pielea uscată iarna | Meddera',
    descriptionRu: 'Сухая кожа зимой: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Pielea uscată iarna: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: сухая кожа зимой.',
    excerptRo: 'Pe scurt: pielea uscată iarna.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'zhirnaya-kozha-leto',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'zhirnaya-kozha-leto-beltsy',
    slugRo: 'piele-grasa-vara-balti',
    publishedAt: '2026-07-12',
    dateModified: '2026-07-12',
    titleRu: 'Жирная кожа летом | Meddera',
    titleRo: 'Pielea grasă vara | Meddera',
    descriptionRu: 'Жирная кожа летом: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Pielea grasă vara: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: жирная кожа летом.',
    excerptRo: 'Pe scurt: pielea grasă vara.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'chuvstvitelnaya-kozha-rutina',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'chuvstvitelnaya-kozha-rutina-beltsy',
    slugRo: 'piele-sensibila-rutina-balti',
    publishedAt: '2026-07-13',
    dateModified: '2026-07-13',
    titleRu: 'Чувствительная кожа | Meddera',
    titleRo: 'Pielea sensibilă | Meddera',
    descriptionRu: 'Чувствительная кожа: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Pielea sensibilă: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: чувствительная кожа.',
    excerptRo: 'Pe scurt: pielea sensibilă.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'vesennie-allergii-kozha',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'vesennie-allergii-kozha-beltsy',
    slugRo: 'alergii-primavara-cutanate-balti',
    publishedAt: '2026-07-14',
    dateModified: '2026-07-14',
    titleRu: 'Весенние аллергии кожи | Meddera',
    titleRo: 'Alergii de primăvară la nivelul pielii | Meddera',
    descriptionRu: 'Весенние аллергии кожи: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Alergii de primăvară la nivelul pielii: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: весенние аллергии кожи.',
    excerptRo: 'Pe scurt: alergii de primăvară la nivelul pielii.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'osennee-vypadenie-volos',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'osennee-vypadenie-volos-beltsy',
    slugRo: 'caderea-parului-sezon-toamna-balti',
    publishedAt: '2026-07-15',
    dateModified: '2026-07-15',
    titleRu: 'Сезонное выпадение волос | Meddera',
    titleRo: 'Căderea sezonieră a părului | Meddera',
    descriptionRu: 'Сезонное выпадение волос: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Căderea sezonieră a părului: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: сезонное выпадение волос.',
    excerptRo: 'Pe scurt: căderea sezonieră a părului.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'kozhnaya-reakciya-pische',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'kozhnaya-reakciya-pische-beltsy',
    slugRo: 'reactie-cutanata-alimentara-balti',
    publishedAt: '2026-07-16',
    dateModified: '2026-07-16',
    titleRu: 'Кожная реакция на продукты | Meddera',
    titleRo: 'Reacție cutanată alimentară | Meddera',
    descriptionRu: 'Кожная реакция на продукты: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Reacție cutanată alimentară: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: кожная реакция на продукты.',
    excerptRo: 'Pe scurt: reacție cutanată alimentară.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fotodermatozy-solnce',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'fotodermatozy-solnce-beltsy',
    slugRo: 'fotodermatoza-soare-balti',
    publishedAt: '2026-07-17',
    dateModified: '2026-07-17',
    titleRu: 'Фотодерматозы | Meddera',
    titleRo: 'Fotodermatoza | Meddera',
    descriptionRu: 'Фотодерматозы: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Fotodermatoza: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: фотодерматозы.',
    excerptRo: 'Pe scurt: fotodermatoza.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mikoz-stop-konsultaciya',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'mikoz-stop-konsultaciya-beltsy',
    slugRo: 'micoza-picioare-consultatie-balti',
    publishedAt: '2026-07-18',
    dateModified: '2026-07-18',
    titleRu: 'Микоз стоп | Meddera',
    titleRo: 'Micoza picioarelor | Meddera',
    descriptionRu: 'Микоз стоп: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Micoza picioarelor: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: микоз стоп.',
    excerptRo: 'Pe scurt: micoza picioarelor.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'rubcy-postakne',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'rubcy-postakne-beltsy',
    slugRo: 'cicatrici-postacnee-balti',
    publishedAt: '2026-07-19',
    dateModified: '2026-07-19',
    titleRu: 'Рубцы постакне | Meddera',
    titleRo: 'Cicatrici post-acnee | Meddera',
    descriptionRu: 'Рубцы постакне: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Cicatrici post-acnee: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: рубцы постакне.',
    excerptRo: 'Pe scurt: cicatrici post-acnee.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'keloidy-risk-prokol',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'keloidy-risk-prokol-beltsy',
    slugRo: 'risc-cheloid-piercing-balti',
    publishedAt: '2026-07-20',
    dateModified: '2026-07-20',
    titleRu: 'Келоидный риск после проколов | Meddera',
    titleRo: 'Risc cheloid după piercing | Meddera',
    descriptionRu: 'Келоидный риск после проколов: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Risc cheloid după piercing: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: келоидный риск после проколов.',
    excerptRo: 'Pe scurt: risc cheloid după piercing.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'gidradenit-hronicheskij',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'gidradenit-hronicheskij-beltsy',
    slugRo: 'hidradenita-cronica-balti',
    publishedAt: '2026-07-21',
    dateModified: '2026-07-21',
    titleRu: 'Гидраденит (хроническая форма) | Meddera',
    titleRo: 'Hidradenită (formă cronică) | Meddera',
    descriptionRu: 'Гидраденит (хроническая форма): информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Hidradenită (formă cronică): material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: гидраденит (хроническая форма).',
    excerptRo: 'Pe scurt: hidradenită (formă cronică).',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'lichen-planus-obzor',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'lichen-planus-obzor-beltsy',
    slugRo: 'lichen-planus-prezentare-balti',
    publishedAt: '2026-07-22',
    dateModified: '2026-07-22',
    titleRu: 'Лишай плоский | Meddera',
    titleRo: 'Lichen planus | Meddera',
    descriptionRu: 'Лишай плоский: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Lichen planus: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: лишай плоский.',
    excerptRo: 'Pe scurt: lichen planus.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'ihthyoz-obzor',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'ihthyoz-obzor-beltsy',
    slugRo: 'ichtioza-prezentare-balti',
    publishedAt: '2026-07-23',
    dateModified: '2026-07-23',
    titleRu: 'Ихтиоз | Meddera',
    titleRo: 'Ihtioza | Meddera',
    descriptionRu: 'Ихтиоз: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Ihtioza: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ихтиоз.',
    excerptRo: 'Pe scurt: ihtioza.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'kronicheskaya-krapivnica',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'kronicheskaya-krapivnica-beltsy',
    slugRo: 'urticarie-cronica-balti',
    publishedAt: '2026-07-24',
    dateModified: '2026-07-24',
    titleRu: 'Хроническая крапивница | Meddera',
    titleRo: 'Urticarie cronică | Meddera',
    descriptionRu: 'Хроническая крапивница: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Urticarie cronică: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: хроническая крапивница.',
    excerptRo: 'Pe scurt: urticarie cronică.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'pyogenic-granuloma',
    kind: 'article',
    clusterId: 'dermatologist',
    slugRu: 'pyogenic-granuloma-beltsy',
    slugRo: 'granulom-piogenic-balti',
    publishedAt: '2026-07-25',
    dateModified: '2026-07-25',
    titleRu: 'Пиогенная гранулёма | Meddera',
    titleRo: 'Granulom pirogenic | Meddera',
    descriptionRu: 'Пиогенная гранулёма: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Granulom pirogenic: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: пиогенная гранулёма.',
    excerptRo: 'Pe scurt: granulom pirogenic.',
    bodyKey: 'dermatologist-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
];
