import type { BlogPost } from '@/blog-data/types';

/** Part 2 articles 26–50 — fillers */

export const fillersArticlesPart2: BlogPost[] = [
  {
    id: 'fillery-nos-korekciya-linej',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-nos-korekciya-linej-beltsy',
    slugRo: 'fillere-nas-corectie-linii-balti',
    publishedAt: '2026-11-03',
    dateModified: '2026-11-03',
    titleRu: 'Филлеры и линии профиля носа | Meddera',
    titleRo: 'Fillere și liniile profilului nazal | Meddera',
    descriptionRu: 'Филлеры и линии профиля носа: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Fillere și liniile profilului nazal: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: филлеры и линии профиля носа.',
    excerptRo: 'Pe scurt: fillere și liniile profilului nazal.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-podglaz-zona-vnimanie',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-podglaz-zona-vnimanie-beltsy',
    slugRo: 'fillere-sub-ochi-zona-atentie-balti',
    publishedAt: '2026-11-04',
    dateModified: '2026-11-04',
    titleRu: 'Подглазная зона | Meddera',
    titleRo: 'Zona sub ochi | Meddera',
    descriptionRu: 'Подглазная зона: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Zona sub ochi: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: подглазная зона.',
    excerptRo: 'Pe scurt: zona sub ochi.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-modulaciya-obema-shek',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-modulaciya-obema-shek-beltsy',
    slugRo: 'fillere-modulare-volum-obraji-balti',
    publishedAt: '2026-11-05',
    dateModified: '2026-11-05',
    titleRu: 'Объём щёк | Meddera',
    titleRo: 'Volumul obrajilor | Meddera',
    descriptionRu: 'Объём щёк: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Volumul obrajilor: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: объём щёк.',
    excerptRo: 'Pe scurt: volumul obrajilor.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-kombinacia-mezoterapiya-lico',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-kombinacia-mezoterapiya-lico-beltsy',
    slugRo: 'fillere-combinatie-mezoterapie-fata-balti',
    publishedAt: '2026-11-06',
    dateModified: '2026-11-06',
    titleRu: 'Филлеры и мезотерапия | Meddera',
    titleRo: 'Fillere și mezoterapie | Meddera',
    descriptionRu: 'Филлеры и мезотерапия: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Fillere și mezoterapie: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: филлеры и мезотерапия.',
    excerptRo: 'Pe scurt: fillere și mezoterapie.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-kombinacia-biorevital',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-kombinacia-biorevital-beltsy',
    slugRo: 'fillere-combinatie-biorevitalizare-balti',
    publishedAt: '2026-11-07',
    dateModified: '2026-11-07',
    titleRu: 'Филлеры и биоревитализация | Meddera',
    titleRo: 'Fillere și biorevitalizare | Meddera',
    descriptionRu: 'Филлеры и биоревитализация: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Fillere și biorevitalizare: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: филлеры и биоревитализация.',
    excerptRo: 'Pe scurt: fillere și biorevitalizare.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-posle-poteri-vesa',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-posle-poteri-vesa-beltsy',
    slugRo: 'fillere-dupa-pierdere-greutate-balti',
    publishedAt: '2026-11-08',
    dateModified: '2026-11-08',
    titleRu: 'После похудения | Meddera',
    titleRo: 'După pierderea în greutate | Meddera',
    descriptionRu: 'После похудения: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'După pierderea în greutate: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: после похудения.',
    excerptRo: 'Pe scurt: după pierderea în greutate.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-asimetriya-posle-travmy',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-asimetriya-posle-travmy-beltsy',
    slugRo: 'fillere-asimetrie-dupa-trauma-balti',
    publishedAt: '2026-11-09',
    dateModified: '2026-11-09',
    titleRu: 'Асимметрия после травмы | Meddera',
    titleRo: 'Asimetrie după traumă | Meddera',
    descriptionRu: 'Асимметрия после травмы: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Asimetrie după traumă: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: асимметрия после травмы.',
    excerptRo: 'Pe scurt: asimetrie după traumă.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-dolgovechnost-zavisit',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-dolgovechnost-zavisit-beltsy',
    slugRo: 'fillere-durata-depinde-balti',
    publishedAt: '2026-11-10',
    dateModified: '2026-11-10',
    titleRu: 'От чего зависит срок | Meddera',
    titleRo: 'De ce depinde durata | Meddera',
    descriptionRu: 'От чего зависит срок: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'De ce depinde durata: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: от чего зависит срок.',
    excerptRo: 'Pe scurt: de ce depinde durata.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-konsultaciya-oczenka-proporcij',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-konsultaciya-oczenka-proporcij-beltsy',
    slugRo: 'fillere-consultatie-proportii-balti',
    publishedAt: '2026-11-11',
    dateModified: '2026-11-11',
    titleRu: 'Оценка пропорций | Meddera',
    titleRo: 'Evaluarea proporțiilor | Meddera',
    descriptionRu: 'Оценка пропорций: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Evaluarea proporțiilor: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: оценка пропорций.',
    excerptRo: 'Pe scurt: evaluarea proporțiilor.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-strategiya-minimalizm',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-strategiya-minimalizm-beltsy',
    slugRo: 'fillere-strategie-minimalism-balti',
    publishedAt: '2026-11-12',
    dateModified: '2026-11-12',
    titleRu: 'Стратегия минимализма | Meddera',
    titleRo: 'Strategia minimalismului | Meddera',
    descriptionRu: 'Стратегия минимализма: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Strategia minimalismului: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: стратегия минимализма.',
    excerptRo: 'Pe scurt: strategia minimalismului.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-strategiya-maksimalizm',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-strategiya-maksimalizm-beltsy',
    slugRo: 'fillere-strategie-volum-balti',
    publishedAt: '2026-11-13',
    dateModified: '2026-11-13',
    titleRu: 'Выраженный объём | Meddera',
    titleRo: 'Volum pronunțat | Meddera',
    descriptionRu: 'Выраженный объём: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Volum pronunțat: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: выраженный объём.',
    excerptRo: 'Pe scurt: volum pronunțat.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-marka-preparata-znach',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-marka-preparata-znach-beltsy',
    slugRo: 'fillere-brand-semnificatie-balti',
    publishedAt: '2026-11-14',
    dateModified: '2026-11-14',
    titleRu: 'Значение бренда препарата | Meddera',
    titleRo: 'Semnificația brandului | Meddera',
    descriptionRu: 'Значение бренда препарата: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Semnificația brandului: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: значение бренда препарата.',
    excerptRo: 'Pe scurt: semnificația brandului.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-tehnika-linejnyh-vectorov',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-tehnika-linejnyh-vectorov-beltsy',
    slugRo: 'fillere-tehnica-vectori-balti',
    publishedAt: '2026-11-15',
    dateModified: '2026-11-15',
    titleRu: 'Векторы коррекции | Meddera',
    titleRo: 'Vectori de corecție | Meddera',
    descriptionRu: 'Векторы коррекции: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Vectori de corecție: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: векторы коррекции.',
    excerptRo: 'Pe scurt: vectori de corecție.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-kontrol-posle-nedeli',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-kontrol-nedelya-beltsy',
    slugRo: 'fillere-control-dupa-saptamana-balti',
    publishedAt: '2026-11-16',
    dateModified: '2026-11-16',
    titleRu: 'Контроль через неделю | Meddera',
    titleRo: 'Control după o săptămână | Meddera',
    descriptionRu: 'Контроль через неделю: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Control după o săptămână: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: контроль через неделю.',
    excerptRo: 'Pe scurt: control după o săptămână.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-oslozhnenie-rannie-znaki',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-oslozhnenie-rannie-znaki-beltsy',
    slugRo: 'fillere-complicatii-semne-timpuriu-balti',
    publishedAt: '2026-11-17',
    dateModified: '2026-11-17',
    titleRu: 'Ранние признаки осложнений | Meddera',
    titleRo: 'Semne timpurii ale complicațiilor | Meddera',
    descriptionRu: 'Ранние признаки осложнений: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Semne timpurii ale complicațiilor: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: ранние признаки осложнений.',
    excerptRo: 'Pe scurt: semne timpurii ale complicațiilor.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-kogda-nuzhna-konsult',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-kogda-nuzhna-konsult-beltsy',
    slugRo: 'fillere-cand-consult-urgent-balti',
    publishedAt: '2026-11-18',
    dateModified: '2026-11-18',
    titleRu: 'Когда срочно к врачу | Meddera',
    titleRo: 'Când mergeți urgent la medic | Meddera',
    descriptionRu: 'Когда срочно к врачу: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Când mergeți urgent la medic: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: когда срочно к врачу.',
    excerptRo: 'Pe scurt: când mergeți urgent la medic.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-i-pregnancy-planning',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-i-pregnancy-planning-beltsy',
    slugRo: 'fillere-planificare-sarcina-balti',
    publishedAt: '2026-11-19',
    dateModified: '2026-11-19',
    titleRu: 'Планирование беременности | Meddera',
    titleRo: 'Planificarea sarcinii | Meddera',
    descriptionRu: 'Планирование беременности: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Planificarea sarcinii: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: планирование беременности.',
    excerptRo: 'Pe scurt: planificarea sarcinii.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-i-kormlenie',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-i-kormlenie-beltsy',
    slugRo: 'fillere-si-alaptare-balti',
    publishedAt: '2026-11-20',
    dateModified: '2026-11-20',
    titleRu: 'Лактация и филлеры | Meddera',
    titleRo: 'Alăptarea și fillerele | Meddera',
    descriptionRu: 'Лактация и филлеры: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Alăptarea și fillerele: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: лактация и филлеры.',
    excerptRo: 'Pe scurt: alăptarea și fillerele.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-posle-stomatologii',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-posle-stomatologii-beltsy',
    slugRo: 'fillere-dupa-stomatologie-balti',
    publishedAt: '2026-11-21',
    dateModified: '2026-11-21',
    titleRu: 'После стоматологии | Meddera',
    titleRo: 'După stomatologie | Meddera',
    descriptionRu: 'После стоматологии: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'După stomatologie: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: после стоматологии.',
    excerptRo: 'Pe scurt: după stomatologie.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-posle-plasticheskoj-ranshe',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-posle-plasticheskoj-ranshe-beltsy',
    slugRo: 'fillere-dupa-chirurgie-estetica-balti',
    publishedAt: '2026-11-22',
    dateModified: '2026-11-22',
    titleRu: 'После хирургии лица | Meddera',
    titleRo: 'După chirurgie facială | Meddera',
    descriptionRu: 'После хирургии лица: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'După chirurgie facială: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: после хирургии лица.',
    excerptRo: 'Pe scurt: după chirurgie facială.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-povtornaya-korekciya-cherez-mesyac',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-povtornaya-korekciya-cherez-mesyac-beltsy',
    slugRo: 'fillere-corectie-dupa-luna-balti',
    publishedAt: '2026-11-23',
    dateModified: '2026-11-23',
    titleRu: 'Коррекция через месяц | Meddera',
    titleRo: 'Corecție după o lună | Meddera',
    descriptionRu: 'Коррекция через месяц: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Corecție după o lună: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: коррекция через месяц.',
    excerptRo: 'Pe scurt: corecție după o lună.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-kombinacia-niti-chitat',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-kombinacia-niti-chitat-beltsy',
    slugRo: 'fillere-combinatie-fire-balti',
    publishedAt: '2026-11-24',
    dateModified: '2026-11-24',
    titleRu: 'Филлеры и нити | Meddera',
    titleRo: 'Fillere și fire | Meddera',
    descriptionRu: 'Филлеры и нити: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Fillere și fire: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: филлеры и нити.',
    excerptRo: 'Pe scurt: fillere și fire.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-estetika-muzhchin-profil',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-estetika-muzhchin-profil-beltsy',
    slugRo: 'fillere-estetica-barbati-profil-balti',
    publishedAt: '2026-11-25',
    dateModified: '2026-11-25',
    titleRu: 'Мужской профиль | Meddera',
    titleRo: 'Profil masculin | Meddera',
    descriptionRu: 'Мужской профиль: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Profil masculin: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: мужской профиль.',
    excerptRo: 'Pe scurt: profil masculin.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-zapis-konsultaciya',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-zapis-konsultaciya-beltsy',
    slugRo: 'fillere-programare-consultatie-balti',
    publishedAt: '2026-11-26',
    dateModified: '2026-11-26',
    titleRu: 'Запись на контурную пластику | Meddera',
    titleRo: 'Programare conturare | Meddera',
    descriptionRu: 'Запись на контурную пластику: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Programare conturare: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: запись на контурную пластику.',
    excerptRo: 'Pe scurt: programare conturare.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-anatomiya-proporcii-lica',
    kind: 'article',
    clusterId: 'fillers',
    slugRu: 'fillery-anatomiya-proporcii-lica-beltsy',
    slugRo: 'fillere-anatomie-proportii-fata-balti',
    publishedAt: '2026-11-27',
    dateModified: '2026-11-27',
    titleRu: 'Пропорции лица и филлеры | Meddera',
    titleRo: 'Proporțiile feței și fillerele | Meddera',
    descriptionRu: 'Пропорции лица и филлеры: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Proporțiile feței și fillerele: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: пропорции лица и филлеры.',
    excerptRo: 'Pe scurt: proporțiile feței și fillerele.',
    bodyKey: 'fillers-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
];
