export type ArticleSection = { h2: string; paragraphs: string[] };
export type FillersArticleCopy = { sectionsRu: ArticleSection[]; sectionsRo: ArticleSection[] };

export const FILLERS_ARTICLE_CONTENT_PART2: Record<string, FillersArticleCopy> = {
  'konturnaya-plastika-nososgubnye-skladki': { sectionsRu: [{ h2: 'Коррекция носогубных складок', paragraphs: ['Филлеры средней/высокой плотности заполняют носогубные складки. Глубокое введение. Объём 1-2 мл на каждую сторону. Длительность 12-18 месяцев. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Corecția pliurilor nazolabiale', paragraphs: ['Fillerele de densitate medie/înaltă umplu pliurile nazolabiale. Introducere profundă. Volum 1-2 ml pe fiecare parte. Durată 12-18 luni. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-sleznaya-borozda': { sectionsRu: [{ h2: 'Коррекция слёзной борозды', paragraphs: ['Мягкие филлеры для области под глазами. Деликатная техника. Убирает тёмные круги, впадины. Объём 0.5-1 мл. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Corecția șantului lacrimal', paragraphs: ['Fillere moi pentru zona de sub ochi. Tehnică delicată. Elimină cercurile întunecate, adâncituri. Volum 0.5-1 ml. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-veski': { sectionsRu: [{ h2: 'Коррекция висков', paragraphs: ['Филлеры восстанавливают объём впалых висков. Плотные филлеры, глубокое введение. Объём 1-2 мл на каждую сторону. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Corecția tâmplelor', paragraphs: ['Fillerele restabilesc volumul tâmplelor adâncite. Fillere dense, introducere profundă. Volum 1-2 ml pe fiecare parte. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-nos': { sectionsRu: [{ h2: 'Безоперационная ринопластика', paragraphs: ['Филлеры корректируют форму носа: горбинку, кончик, асимметрию. Плотные филлеры. Объём 0.5-1 мл. Результат временный (12-18 месяцев). Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Rinoplastie non-chirurgicală', paragraphs: ['Fillerele corectează forma nasului: cocoașă, vârf, asimetrie. Fillere dense. Volum 0.5-1 ml. Rezultat temporar (12-18 luni). Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-podborodok': { sectionsRu: [{ h2: 'Коррекция подбородка', paragraphs: ['Филлеры увеличивают подбородок, улучшают профиль. Плотные филлеры. Объём 1-3 мл. Длительность 12-18 месяцев. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Corecția bărbiei', paragraphs: ['Fillerele măresc bărbia, îmbunătățesc profilul. Fillere dense. Volum 1-3 ml. Durată 12-18 luni. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-skuly': { sectionsRu: [{ h2: 'Коррекция скул', paragraphs: ['Филлеры создают выразительные скулы. Плотные филлеры, глубокое введение. Объём 1-2 мл на каждую сторону. Длительность 12-18 месяцев. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Corecția pomeților', paragraphs: ['Fillerele creează pomeți expresivi. Fillere dense, introducere profundă. Volum 1-2 ml pe fiecare parte. Durată 12-18 luni. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-shcheki': { sectionsRu: [{ h2: 'Коррекция щёк', paragraphs: ['Филлеры восстанавливают объём щёк (возрастная потеря). Средней плотности филлеры. Объём 1-2 мл на каждую сторону. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Corecția obrajilor', paragraphs: ['Fillerele restabilesc volumul obrajilor (pierdere legată de vârstă). Fillere de densitate medie. Volum 1-2 ml pe fiecare parte. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-ugolkov-rta': { sectionsRu: [{ h2: 'Коррекция уголков рта', paragraphs: ['Филлеры приподнимают опущенные уголки рта. Мягкие филлеры. Объём 0.3-0.5 мл. Длительность 6-12 месяцев. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Corecția colțurilor gurii', paragraphs: ['Fillerele ridică colțurile coborâte ale gurii. Fillere moi. Volum 0.3-0.5 ml. Durată 6-12 luni. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-rezultaty-dlitelnost': { sectionsRu: [{ h2: 'Результаты и длительность', paragraphs: ['Результат виден сразу. Максимальный эффект через 2 недели (отёк проходит). Длительность: 6-18 месяцев (зависит от зоны, плотности филлера). Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Rezultate și durată', paragraphs: ['Rezultatul este vizibil imediat. Efect maxim în 2 săptămâni (edemul trece). Durată: 6-18 luni (depinde de zonă, densitatea fillerului). Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-protivopokazaniya': { sectionsRu: [{ h2: 'Противопоказания', paragraphs: ['Беременность, кормление, аллергия на ГК, активная инфекция, онкология, тяжёлые системные заболевания. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Contraindicații', paragraphs: ['Sarcină, alăptare, alergie la AH, infecție activă, oncologie, boli sistemice grave. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-uhod-posle': { sectionsRu: [{ h2: 'Уход после процедуры', paragraphs: ['Не трогать лицо, не наносить макияж 24 часа. Избегать солнца, сауны, спорта 2-3 дня. SPF 30-50. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Îngrijire după procedură', paragraphs: ['Nu atingeți fața, nu aplicați machiaj 24 ore. Evitați soarele, sauna, sportul 2-3 zile. SPF 30-50. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-bolevye-oshchushcheniya': { sectionsRu: [{ h2: 'Болевые ощущения', paragraphs: ['Малоболезненная процедура. Используется анестезирующий крем, филлеры с лидокаином. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Senzații dureroase', paragraphs: ['Procedură puțin dureroasă. Se folosește cremă anestezianta, fillere cu lidocaină. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-otek-sinyaki': { sectionsRu: [{ h2: 'Отёк и синяки', paragraphs: ['Лёгкий отёк — норма (1-3 дня). Синяки у 10-30% пациентов (5-10 дней). Холодные компрессы, арника. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Edem și vânătăi', paragraphs: ['Edem ușor — normă (1-3 zile). Vânătăi la 10-30% pacienți (5-10 zile). Comprese reci, arnica. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-vozrast': { sectionsRu: [{ h2: 'Оптимальный возраст', paragraphs: ['С 25-30 лет (профилактика, коррекция формы). После 35-40 лет — восполнение объёма, омоложение. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Vârsta optimă', paragraphs: ['De la 25-30 ani (prevenire, corecția formei). După 35-40 ani — restabilirea volumului, întinerire. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-rastvorenie-gialuronidazoj': { sectionsRu: [{ h2: 'Растворение филлеров', paragraphs: ['Гиалуронидаза растворяет филлеры при неудовлетворительном результате, осложнениях. Результат через 24-48 часов. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Dizolvarea fillerelor', paragraphs: ['Hialuronidaza dizolvă fillerele la rezultat nesatisfăcător, complicații. Rezultat în 24-48 ore. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-oslozhneniya': { sectionsRu: [{ h2: 'Возможные осложнения', paragraphs: ['Отёк, синяки (норма). Редко: некроз (нарушение кровоснабжения), миграция филлера, уплотнения. При осложнениях — немедленно к врачу. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Complicații posibile', paragraphs: ['Edem, vânătăi (normă). Rar: necroză (tulburare de circulație), migrarea fillerului, indurații. La complicații — imediat la medic. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-vs-botoks': { sectionsRu: [{ h2: 'Разница', paragraphs: ['Филлеры — объём. Ботокс — расслабление мышц, разглаживание морщин. Разные цели. Можно сочетать. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Diferența', paragraphs: ['Fillerele — volum. Botoxul — relaxarea mușchilor, netezirea ridurilor. Scopuri diferite. Se pot combina. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-kombinaciya-procedur': { sectionsRu: [{ h2: 'Комбинация', paragraphs: ['Филлеры можно сочетать с ботоксом, мезотерапией, биоревитализацией (интервал 2 недели). Комплексный подход даёт лучший результат. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Combinare', paragraphs: ['Fillerele se pot combina cu botox, mezoterapie, biorevitalizare (interval 2 săptămâni). Abordarea complexă oferă rezultat mai bun. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-sezon': { sectionsRu: [{ h2: 'Лучший сезон', paragraphs: ['Можно круглый год. Осень-зима — оптимально (меньше солнца). Летом — SPF 30-50, избегать прямого солнца. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Cel mai bun sezon', paragraphs: ['Se poate tot anul. Toamna-iarna — optim (mai puțin soare). Vara — SPF 30-50, evitați soarele direct. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-muzhchinam': { sectionsRu: [{ h2: 'Филлеры для мужчин', paragraphs: ['Мужчинам нужен более сдержанный результат (не женственный). Коррекция подбородка, скул, носогубных складок. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Fillere pentru bărbați', paragraphs: ['Bărbații au nevoie de rezultat mai reținut (nu feminin). Corecția bărbiei, pomeților, pliurilor nazolabiale. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-povtornaya-procedura': { sectionsRu: [{ h2: 'Повторная процедура', paragraphs: ['Повторная контурная пластика через 6-18 месяцев (когда объём уменьшился на 30-50%). Не ждите полного рассасывания. Запись в Meddera: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }], sectionsRo: [{ h2: 'Procedură repetată', paragraphs: ['Conturarea repetată în 6-18 luni (când volumul a scăzut cu 30-50%). Nu așteptați resorbția completă. Programare la Meddera: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }] },
  'konturnaya-plastika-skul-podborodka': { 
    sectionsRu: [
      { h2: 'Комплексная коррекция скул и подбородка', paragraphs: ['Филлеры для скул и подбородка часто используются вместе для гармонизации пропорций лица. Скулы создают выразительность, подбородок улучшает профиль.', 'Плотные филлеры вводятся глубоко в область скул (1-2 мл на каждую сторону) и подбородка (1-3 мл). Результат виден сразу, максимальный эффект через 2 недели.', 'Длительность эффекта: 12-18 месяцев. Комплексная коррекция даёт более выраженный результат омоложения и улучшения пропорций лица.'] },
      { h2: 'Показания для комплексной коррекции', paragraphs: ['Возрастная потеря объёма скул и подбородка (после 35-40 лет). Слабовыраженные скулы и подбородок (генетическая особенность).', 'Асимметрия лица, требующая коррекции в нескольких зонах. Желание улучшить пропорции лица без операции.'] },
      { h2: 'Техника введения филлеров', paragraphs: ['Врач оценивает пропорции лица, определяет объём филлера для каждой зоны. Используются плотные филлеры с высокой когезивностью.', 'Введение в скулы: глубокое, на уровне надкостницы. Введение в подбородок: глубокое, для создания проекции и улучшения профиля.', 'Процедура занимает 30-40 минут. Используется анестезирующий крем, филлеры с лидокаином.'] },
      { h2: 'Результаты и восстановление', paragraphs: ['Результат виден сразу после процедуры. Лёгкий отёк 1-3 дня (норма). Синяки возможны у 10-30% пациентов (5-10 дней).', 'Максимальный эффект через 2 недели, когда отёк полностью проходит. Длительность эффекта: 12-18 месяцев.', 'Рекомендации после процедуры: не трогать лицо 24 часа, избегать солнца, сауны, спорта 2-3 дня, использовать SPF 30-50.'] },
      { h2: 'Контурная пластика в клинике Meddera', paragraphs: ['В Meddera используются сертифицированные филлеры от ведущих производителей. Процедуру проводит опытный врач-косметолог.', 'Консультация включает: оценку пропорций лица, выбор зон коррекции, расчёт объёма филлера и стоимости.', 'Запись на консультацию: 400 MDL (первичная), 250 MDL (повторная). Адрес: Бельцы, ул. Штефан чел Маре, 13.'] }
    ],
    sectionsRo: [
      { h2: 'Corecția complexă a pomeților și bărbiei', paragraphs: ['Fillerele pentru pomeți și bărbie sunt adesea folosite împreună pentru armonizarea proporțiilor feței. Pomețiicrează expresivitate, bărbia îmbunătățește profilul.', 'Fillere dense sunt introduse adânc în zona pomeților (1-2 ml pe fiecare parte) și bărbie (1-3 ml). Rezultatul este vizibil imediat, efect maxim în 2 săptămâni.', 'Durata efectului: 12-18 luni. Corecția complexă oferă un rezultat mai pronunțat de întinerire și îmbunătățire a proporțiilor feței.'] },
      { h2: 'Indicații pentru corecția complexă', paragraphs: ['Pierderea volumului pomeților și bărbiei legată de vârstă (după 35-40 ani). Pomeți și bărbie slab pronunțate (particularitate genetică).', 'Asimetria feței, necesitând corecție în mai multe zone. Dorința de a îmbunătăți proporțiile feței fără operație.'] },
      { h2: 'Tehnica de introducere a fillerelor', paragraphs: ['Medicul evaluează proporțiile feței, determină volumul de filler pentru fiecare zonă. Se folosesc fillere dense cu coezivitate înaltă.', 'Introducerea în pomeți: profundă, la nivelul periostului. Introducerea în bărbie: profundă, pentru crearea proiecției și îmbunătățirea profilului.', 'Procedura durează 30-40 minute. Se folosește cremă anestezianta, fillere cu lidocaină.'] },
      { h2: 'Rezultate și recuperare', paragraphs: ['Rezultatul este vizibil imediat după procedură. Edem ușor 1-3 zile (normă). Vânătăi posibile la 10-30% pacienți (5-10 zile).', 'Efect maxim în 2 săptămâni, când edemul trece complet. Durata efectului: 12-18 luni.', 'Recomandări după procedură: nu atingeți fața 24 ore, evitați soarele, sauna, sportul 2-3 zile, folosiți SPF 30-50.'] },
      { h2: 'Conturarea facială la clinica Meddera', paragraphs: ['La Meddera folosim fillere certificate de la producători de top. Procedura este efectuată de un medic cosmetolog experimentat.', 'Consultația include: evaluarea proporțiilor feței, alegerea zonelor de corecție, calculul volumului de filler și costului.', 'Programare la consultație: 400 MDL (primară), 250 MDL (repetată). Adresa: Bălți, str. Ștefan cel Mare, 13.'] }
    ]
  },
};
