import type { BlogPost } from '@/blog-data/types';

/**
 * Рубрика "Увеличение губ в Бельцах" — часть 1 (статьи 1-25)
 * Дополнение к существующему хабу lip-augmentation-hub
 */

export const lipsArticlesPart1: BlogPost[] = [
  {
    id: 'uvelichenie-gub-beltsy-vidy-fillerov',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-beltsy-vidy-fillerov',
    slugRo: 'marirea-buzelor-balti-tipuri-fillere',
    publishedAt: '2026-04-10',
    dateModified: '2026-04-10',
    titleRu: 'Увеличение губ в Бельцах: виды филлеров | Meddera',
    titleRo: 'Mărirea buzelor în Bălți: tipuri de fillere | Meddera',
    descriptionRu: 'Виды филлеров для увеличения губ: гиалуроновая кислота, плотность, производители. Консультация в Meddera.',
    descriptionRo: 'Tipuri de fillere pentru mărirea buzelor: acid hialuronic, densitate, producători. Consultație la Meddera.',
    excerptRu: 'Какие филлеры используются для увеличения губ и как выбрать подходящий.',
    excerptRo: 'Ce fillere se folosesc pentru mărirea buzelor și cum să alegeți cel potrivit.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-forma-simmetriya',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-forma-simmetriya-beltsy',
    slugRo: 'marirea-buzelor-forma-simetrie-balti',
    publishedAt: '2026-04-10',
    dateModified: '2026-04-10',
    titleRu: 'Увеличение губ: форма и симметрия | Meddera, Бельцы',
    titleRo: 'Mărirea buzelor: formă și simetrie | Meddera, Bălți',
    descriptionRu: 'Как выбрать форму губ при увеличении: пропорции, симметрия, гармония с лицом. Консультация в Meddera.',
    descriptionRo: 'Cum să alegeți forma buzelor la mărire: proporții, simetrie, armonie cu fața. Consultație la Meddera.',
    excerptRu: 'Принципы выбора формы губ для естественного результата.',
    excerptRo: 'Principiile alegerii formei buzelor pentru rezultat natural.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-uhod-posle-procedury',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-uhod-posle-procedury-beltsy',
    slugRo: 'marirea-buzelor-ingrijire-dupa-procedura-balti',
    publishedAt: '2026-04-10',
    dateModified: '2026-04-10',
    titleRu: 'Увеличение губ: уход после процедуры | Meddera',
    titleRo: 'Mărirea buzelor: îngrijire după procedură | Meddera',
    descriptionRu: 'Рекомендации после увеличения губ: что можно, что нельзя, как ухаживать. Клиника Meddera, Бельцы.',
    descriptionRo: 'Recomandări după mărirea buzelor: ce se poate, ce nu se poate, cum să îngrijiți. Clinica Meddera, Bălți.',
    excerptRu: 'Правила ухода за губами после инъекций филлеров.',
    excerptRo: 'Reguli de îngrijire a buzelor după injecțiile cu fillere.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-oslozhneniya-profilaktika',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-oslozhneniya-profilaktika-beltsy',
    slugRo: 'marirea-buzelor-complicatii-profilaxie-balti',
    publishedAt: '2026-04-17',
    dateModified: '2026-04-17',
    titleRu: 'Увеличение губ: осложнения и профилактика | Meddera',
    titleRo: 'Mărirea buzelor: complicații și profilaxie | Meddera',
    descriptionRu: 'Возможные осложнения после увеличения губ и как их избежать. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Complicații posibile după mărirea buzelor și cum să le evitați. Consultație la Meddera, Bălți.',
    excerptRu: 'Как минимизировать риски и что делать при осложнениях.',
    excerptRo: 'Cum să minimizați riscurile și ce să faceți în caz de complicații.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-dlitelnost-effekta',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-dlitelnost-effekta-beltsy',
    slugRo: 'marirea-buzelor-durata-efectului-balti',
    publishedAt: '2026-04-17',
    dateModified: '2026-04-17',
    titleRu: 'Сколько держится увеличение губ | Meddera, Бельцы',
    titleRo: 'Cât ține mărirea buzelor | Meddera, Bălți',
    descriptionRu: 'Длительность эффекта увеличения губ филлерами. Что влияет на результат. Консультация в Meddera.',
    descriptionRo: 'Durata efectului măririi buzelor cu fillere. Ce influențează rezultatul. Consultație la Meddera.',
    excerptRu: 'Как долго держится результат и когда повторять процедуру.',
    excerptRo: 'Cât timp ține rezultatul și când să repetați procedura.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-estestvenny-rezultat',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-estestvennyj-rezultat-beltsy',
    slugRo: 'marirea-buzelor-rezultat-natural-balti',
    publishedAt: '2026-04-24',
    dateModified: '2026-04-24',
    titleRu: 'Естественное увеличение губ без перебора | Meddera',
    titleRo: 'Mărirea naturală a buzelor fără exagerare | Meddera',
    descriptionRu: 'Как добиться естественного результата при увеличении губ. Принципы гармонии. Консультация в Бельцах.',
    descriptionRo: 'Cum să obțineți rezultat natural la mărirea buzelor. Principii de armonie. Consultație în Bălți.',
    excerptRu: 'Секреты естественного увеличения губ.',
    excerptRo: 'Secretele măririi naturale a buzelor.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-tonkie-guby',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-tonkie-guby-beltsy',
    slugRo: 'marirea-buzelor-buze-subtiri-balti',
    publishedAt: '2026-04-24',
    dateModified: '2026-04-24',
    titleRu: 'Увеличение тонких губ: особенности | Meddera, Бельцы',
    titleRo: 'Mărirea buzelor subțiri: particularități | Meddera, Bălți',
    descriptionRu: 'Особенности увеличения тонких губ филлерами. Техника, дозировка. Консультация в Meddera.',
    descriptionRo: 'Particularitățile măririi buzelor subțiri cu fillere. Tehnică, dozaj. Consultație la Meddera.',
    excerptRu: 'Как увеличить тонкие губы безопасно и красиво.',
    excerptRo: 'Cum să măriți buzele subțiri în siguranță și frumos.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-asimmetriya-korrekciya',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-asimmetriya-korrekciya-beltsy',
    slugRo: 'marirea-buzelor-asimetrie-corectie-balti',
    publishedAt: '2026-05-01',
    dateModified: '2026-05-01',
    titleRu: 'Коррекция асимметрии губ филлерами | Meddera',
    titleRo: 'Corecția asimetriei buzelor cu fillere | Meddera',
    descriptionRu: 'Как исправить асимметрию губ с помощью филлеров. Техника коррекции. Консультация в Бельцах.',
    descriptionRo: 'Cum să corectați asimetria buzelor cu ajutorul fillerelor. Tehnică de corecție. Consultație în Bălți.',
    excerptRu: 'Коррекция асимметричных губ для гармоничного результата.',
    excerptRo: 'Corecția buzelor asimetrice pentru rezultat armonios.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-kontury-chetkost',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-kontury-chetkost-beltsy',
    slugRo: 'marirea-buzelor-contururi-claritate-balti',
    publishedAt: '2026-05-01',
    dateModified: '2026-05-01',
    titleRu: 'Контурирование губ филлерами | Meddera, Бельцы',
    titleRo: 'Conturarea buzelor cu fillere | Meddera, Bălți',
    descriptionRu: 'Как сделать контур губ чётким с помощью филлеров. Техника контурирования. Консультация в Meddera.',
    descriptionRo: 'Cum să faceți conturul buzelor clar cu ajutorul fillerelor. Tehnică de conturare. Consultație la Meddera.',
    excerptRu: 'Чёткий контур губ для выразительности.',
    excerptRo: 'Contur clar al buzelor pentru expresivitate.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-verkhnyaya-nizhnyaya',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-verkhnyaya-nizhnyaya-beltsy',
    slugRo: 'marirea-buzelor-superioara-inferioara-balti',
    publishedAt: '2026-05-08',
    dateModified: '2026-05-08',
    titleRu: 'Увеличение верхней или нижней губы | Meddera',
    titleRo: 'Mărirea buzei superioare sau inferioare | Meddera',
    descriptionRu: 'Как увеличить только верхнюю или нижнюю губу. Пропорции, гармония. Консультация в Бельцах.',
    descriptionRo: 'Cum să măriți doar buza superioară sau inferioară. Proporții, armonie. Consultație în Bălți.',
    excerptRu: 'Коррекция одной губы для баланса.',
    excerptRo: 'Corecția unei buze pentru echilibru.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-vozrastnye-izmeneniya',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-vozrastnye-izmeneniya-beltsy',
    slugRo: 'marirea-buzelor-modificari-varsta-balti',
    publishedAt: '2026-05-08',
    dateModified: '2026-05-08',
    titleRu: 'Увеличение губ после 40-50 лет | Meddera, Бельцы',
    titleRo: 'Mărirea buzelor după 40-50 ani | Meddera, Bălți',
    descriptionRu: 'Особенности увеличения губ в зрелом возрасте. Восполнение объёма, коррекция морщин. Консультация в Meddera.',
    descriptionRo: 'Particularitățile măririi buzelor la vârstă matură. Restabilirea volumului, corecția ridurilor. Consultație la Meddera.',
    excerptRu: 'Омоложение губ филлерами после 40.',
    excerptRo: 'Întinerirea buzelor cu fillere după 40.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-morshchiny-vokrug',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-morshchiny-vokrug-beltsy',
    slugRo: 'marirea-buzelor-riduri-jurul-balti',
    publishedAt: '2026-05-15',
    dateModified: '2026-05-15',
    titleRu: 'Филлеры от морщин вокруг губ | Meddera, Бельцы',
    titleRo: 'Fillere pentru ridurile din jurul buzelor | Meddera, Bălți',
    descriptionRu: 'Коррекция кисетных морщин вокруг губ филлерами. Техника, результаты. Консультация в Meddera.',
    descriptionRo: 'Corecția ridurilor periorbitale din jurul buzelor cu fillere. Tehnică, rezultate. Consultație la Meddera.',
    excerptRu: 'Как убрать морщины вокруг рта филлерами.',
    excerptRo: 'Cum să eliminați ridurile din jurul gurii cu fillere.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-nososgubnye-skladki',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-nososgubnye-skladki-beltsy',
    slugRo: 'marirea-buzelor-pliuri-nazolabiale-balti',
    publishedAt: '2026-05-15',
    dateModified: '2026-05-15',
    titleRu: 'Филлеры губ и носогубных складок | Meddera',
    titleRo: 'Fillere pentru buze și pliuri nazolabiale | Meddera',
    descriptionRu: 'Комплексная коррекция губ и носогубных складок. Гармоничное омоложение. Консультация в Бельцах.',
    descriptionRo: 'Corecție complexă a buzelor și pliurilor nazolabiale. Întinerire armonioasă. Consultație în Bălți.',
    excerptRu: 'Комплексный подход к омоложению нижней трети лица.',
    excerptRo: 'Abordare complexă pentru întinerirea treimii inferioare a feței.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-gialuronovaya-kislota',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-gialuronovaya-kislota-beltsy',
    slugRo: 'marirea-buzelor-acid-hialuronic-balti',
    publishedAt: '2026-05-22',
    dateModified: '2026-05-22',
    titleRu: 'Гиалуроновая кислота для губ: как работает | Meddera',
    titleRo: 'Acidul hialuronic pentru buze: cum funcționează | Meddera',
    descriptionRu: 'Как гиалуроновая кислота увеличивает губы. Механизм действия, безопасность. Консультация в Meddera.',
    descriptionRo: 'Cum mărește acidul hialuronic buzele. Mecanism de acțiune, siguranță. Consultație la Meddera.',
    excerptRu: 'Всё о гиалуроновой кислоте для увеличения губ.',
    excerptRo: 'Tot despre acidul hialuronic pentru mărirea buzelor.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-plotnost-fillera',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-plotnost-fillera-beltsy',
    slugRo: 'marirea-buzelor-densitate-filler-balti',
    publishedAt: '2026-05-22',
    dateModified: '2026-05-22',
    titleRu: 'Плотность филлера для губ: как выбрать | Meddera',
    titleRo: 'Densitatea fillerului pentru buze: cum să alegeți | Meddera',
    descriptionRu: 'Какая плотность филлера нужна для губ. Мягкие и плотные филлеры. Консультация в Бельцах.',
    descriptionRo: 'Ce densitate de filler este necesară pentru buze. Fillere moi și dense. Consultație în Bălți.',
    excerptRu: 'Выбор плотности филлера для естественного результата.',
    excerptRo: 'Alegerea densității fillerului pentru rezultat natural.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-proizvoditeli-fillerov',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-proizvoditeli-fillerov-beltsy',
    slugRo: 'marirea-buzelor-producatori-fillere-balti',
    publishedAt: '2026-05-29',
    dateModified: '2026-05-29',
    titleRu: 'Производители филлеров для губ | Meddera, Бельцы',
    titleRo: 'Producători de fillere pentru buze | Meddera, Bălți',
    descriptionRu: 'Популярные бренды филлеров: Juvederm, Restylane, Belotero. Сравнение, выбор. Консультация в Meddera.',
    descriptionRo: 'Branduri populare de fillere: Juvederm, Restylane, Belotero. Comparație, alegere. Consultație la Meddera.',
    excerptRu: 'Какие филлеры лучше для увеличения губ.',
    excerptRo: 'Ce fillere sunt mai bune pentru mărirea buzelor.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-bolevye-oshchushcheniya',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-bolevye-oshchushcheniya-beltsy',
    slugRo: 'marirea-buzelor-senzatii-dureroase-balti',
    publishedAt: '2026-05-29',
    dateModified: '2026-05-29',
    titleRu: 'Больно ли увеличивать губы | Meddera, Бельцы',
    titleRo: 'Este dureros să măriți buzele | Meddera, Bălți',
    descriptionRu: 'Болевые ощущения при увеличении губ. Анестезия, комфорт. Консультация в Meddera.',
    descriptionRo: 'Senzații dureroase la mărirea buzelor. Anestezie, confort. Consultație la Meddera.',
    excerptRu: 'Как проходит процедура и насколько это больно.',
    excerptRo: 'Cum decurge procedura și cât de dureros este.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-otek-sinyaki',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-otek-sinyaki-beltsy',
    slugRo: 'marirea-buzelor-edem-vanatai-balti',
    publishedAt: '2026-06-05',
    dateModified: '2026-06-05',
    titleRu: 'Отёк и синяки после увеличения губ | Meddera',
    titleRo: 'Edem și vânătăi după mărirea buzelor | Meddera',
    descriptionRu: 'Что нормально после увеличения губ: отёк, синяки. Как ускорить восстановление. Консультация в Бельцах.',
    descriptionRo: 'Ce este normal după mărirea buzelor: edem, vânătăi. Cum să accelerați recuperarea. Consultație în Bălți.',
    excerptRu: 'Восстановление после увеличения губ.',
    excerptRo: 'Recuperare după mărirea buzelor.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-rastvorenie-gialuronidazoj',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-rastvorenie-gialuronidazoj-beltsy',
    slugRo: 'marirea-buzelor-dizolvare-hialuronidaza-balti',
    publishedAt: '2026-06-05',
    dateModified: '2026-06-05',
    titleRu: 'Растворение филлера губ гиалуронидазой | Meddera',
    titleRo: 'Dizolvarea fillerului buzelor cu hialuronidază | Meddera',
    descriptionRu: 'Когда и как растворяют филлер в губах. Гиалуронидаза, показания. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Când și cum se dizolvă fillerul în buze. Hialuronidază, indicații. Consultație la Meddera, Bălți.',
    excerptRu: 'Как убрать филлер, если результат не понравился.',
    excerptRo: 'Cum să eliminați fillerul dacă rezultatul nu a plăcut.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-pervyj-raz',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-pervyj-raz-beltsy',
    slugRo: 'marirea-buzelor-prima-data-balti',
    publishedAt: '2026-06-12',
    dateModified: '2026-06-12',
    titleRu: 'Увеличение губ в первый раз: что нужно знать | Meddera',
    titleRo: 'Mărirea buzelor prima dată: ce trebuie să știți | Meddera',
    descriptionRu: 'Первое увеличение губ: подготовка, процедура, результат. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Prima mărire a buzelor: pregătire, procedură, rezultat. Consultație la Meddera, Bălți.',
    excerptRu: 'Всё, что нужно знать перед первым увеличением губ.',
    excerptRo: 'Tot ce trebuie să știți înainte de prima mărire a buzelor.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-povtornaya-procedura',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-povtornaya-procedura-beltsy',
    slugRo: 'marirea-buzelor-procedura-repetata-balti',
    publishedAt: '2026-06-12',
    dateModified: '2026-06-12',
    titleRu: 'Повторное увеличение губ: когда и как | Meddera',
    titleRo: 'Mărirea repetată a buzelor: când și cum | Meddera',
    descriptionRu: 'Когда делать повторное увеличение губ. Частота процедур, накопительный эффект. Консультация в Meddera.',
    descriptionRo: 'Când să faceți mărirea repetată a buzelor. Frecvența procedurilor, efect cumulativ. Consultație la Meddera.',
    excerptRu: 'Как поддерживать результат увеличения губ.',
    excerptRo: 'Cum să mențineți rezultatul măririi buzelor.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-protivopokazaniya',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-protivopokazaniya-beltsy',
    slugRo: 'marirea-buzelor-contraindicatii-balti',
    publishedAt: '2026-06-19',
    dateModified: '2026-06-19',
    titleRu: 'Противопоказания к увеличению губ | Meddera',
    titleRo: 'Contraindicații la mărirea buzelor | Meddera',
    descriptionRu: 'Когда нельзя увеличивать губы филлерами. Абсолютные и относительные противопоказания. Консультация в Бельцах.',
    descriptionRo: 'Când nu se pot mări buzele cu fillere. Contraindicații absolute și relative. Consultație în Bălți.',
    excerptRu: 'Кому противопоказано увеличение губ.',
    excerptRo: 'Cui este contraindicată mărirea buzelor.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-gerpes-profilaktika',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-gerpes-profilaktika-beltsy',
    slugRo: 'marirea-buzelor-herpes-profilaxie-balti',
    publishedAt: '2026-06-19',
    dateModified: '2026-06-19',
    titleRu: 'Увеличение губ и герпес: профилактика | Meddera',
    titleRo: 'Mărirea buzelor și herpesul: profilaxie | Meddera',
    descriptionRu: 'Как избежать обострения герпеса после увеличения губ. Профилактика, лечение. Консультация в Meddera.',
    descriptionRo: 'Cum să evitați exacerbarea herpesului după mărirea buzelor. Profilaxie, tratament. Consultație la Meddera.',
    excerptRu: 'Профилактика герпеса при увеличении губ.',
    excerptRo: 'Profilaxia herpesului la mărirea buzelor.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'uvelichenie-gub-sezon-vremya-goda',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'uvelichenie-gub-sezon-vremya-goda-beltsy',
    slugRo: 'marirea-buzelor-sezon-anotimp-balti',
    publishedAt: '2026-06-26',
    dateModified: '2026-06-26',
    titleRu: 'В какое время года лучше увеличивать губы | Meddera',
    titleRo: 'În ce anotimp este mai bine să măriți buzele | Meddera',
    descriptionRu: 'Влияет ли сезон на результат увеличения губ. Лето, зима, межсезонье. Консультация в Бельцах.',
    descriptionRo: 'Influențează anotimpul rezultatul măririi buzelor. Vară, iarnă, intersezoane. Consultație în Bălți.',
    excerptRu: 'Когда лучше делать увеличение губ.',
    excerptRo: 'Când este mai bine să faceți mărirea buzelor.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
];
