import type { BlogPost } from '@/blog-data/types';

/** Part 2 articles 26–50 — lips */

export const lipsArticlesPart2: BlogPost[] = [
  {
    id: 'guby-forma-serdce',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-forma-serdce-beltsy',
    slugRo: 'buze-forma-inima-balti',
    publishedAt: '2026-08-20',
    dateModified: '2026-08-20',
    titleRu: 'Форма губ «сердце» | Meddera',
    titleRo: 'Forma buzelor în inimă | Meddera',
    descriptionRu: 'Форма губ «сердце»: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Forma buzelor în inimă: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: форма губ «сердце».',
    excerptRo: 'Pe scurt: forma buzelor în inimă.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-forma-lukovichka',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-forma-lukovichka-beltsy',
    slugRo: 'buze-forma-lamina-balti',
    publishedAt: '2026-08-21',
    dateModified: '2026-08-21',
    titleRu: 'Форма «луковичка» | Meddera',
    titleRo: 'Forma în bulb | Meddera',
    descriptionRu: 'Форма «луковичка»: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Forma în bulb: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: форма «луковичка».',
    excerptRo: 'Pe scurt: forma în bulb.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-asimetriya-posle-travmy',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-asimetriya-posle-travmy-beltsy',
    slugRo: 'asimetrie-buze-dupa-trauma-balti',
    publishedAt: '2026-08-22',
    dateModified: '2026-08-22',
    titleRu: 'Асимметрия после травмы | Meddera',
    titleRo: 'Asimetrie după traumă | Meddera',
    descriptionRu: 'Асимметрия после травмы: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Asimetrie după traumă: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: асимметрия после травмы.',
    excerptRo: 'Pe scurt: asimetrie după traumă.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'fillery-guby-marki-sravnenie',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'fillery-guby-marki-sravnenie-beltsy',
    slugRo: 'fillere-buze-branduri-comparatie-balti',
    publishedAt: '2026-08-23',
    dateModified: '2026-08-23',
    titleRu: 'Бренды филлеров для губ | Meddera',
    titleRo: 'Branduri de fillere pentru buze | Meddera',
    descriptionRu: 'Бренды филлеров для губ: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Branduri de fillere pentru buze: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: бренды филлеров для губ.',
    excerptRo: 'Pe scurt: branduri de fillere pentru buze.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-estetika-balans-licza',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-estetika-balans-licza-beltsy',
    slugRo: 'buze-estetica-balanta-fata-balti',
    publishedAt: '2026-08-24',
    dateModified: '2026-08-24',
    titleRu: 'Баланс губ и лица | Meddera',
    titleRo: 'Balans buze-față | Meddera',
    descriptionRu: 'Баланс губ и лица: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Balans buze-față: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: баланс губ и лица.',
    excerptRo: 'Pe scurt: balans buze-față.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-korekciya-tonkih-konicheskih',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-korekciya-tonkih-konicheskih-beltsy',
    slugRo: 'buze-subti-corectie-balti',
    publishedAt: '2026-08-25',
    dateModified: '2026-08-25',
    titleRu: 'Тонкие губы: коррекция | Meddera',
    titleRo: 'Buze subțiri: corecție | Meddera',
    descriptionRu: 'Тонкие губы: коррекция: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Buze subțiri: corecție: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: тонкие губы: коррекция.',
    excerptRo: 'Pe scurt: buze subțiri: corecție.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-korekciya-opuschennyh-ugolkov',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-korekciya-opuschennyh-ugolkov-beltsy',
    slugRo: 'buze-colturi-coborate-balti',
    publishedAt: '2026-08-26',
    dateModified: '2026-08-26',
    titleRu: 'Опущенные уголки рта | Meddera',
    titleRo: 'Colțuri coborâte ale gurii | Meddera',
    descriptionRu: 'Опущенные уголки рта: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Colțuri coborâte ale gurii: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: опущенные уголки рта.',
    excerptRo: 'Pe scurt: colțuri coborâte ale gurii.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-posle-rastyazheniya',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-posle-rastyazheniya-beltsy',
    slugRo: 'buze-dupa-intindere-balti',
    publishedAt: '2026-08-27',
    dateModified: '2026-08-27',
    titleRu: 'Губы после растяжений | Meddera',
    titleRo: 'Buze după întinderi | Meddera',
    descriptionRu: 'Губы после растяжений: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Buze după întinderi: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: губы после растяжений.',
    excerptRo: 'Pe scurt: buze după întinderi.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-i-komicheskie-linii',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-i-komicheskie-linii-beltsy',
    slugRo: 'buze-linii-comice-balti',
    publishedAt: '2026-08-28',
    dateModified: '2026-08-28',
    titleRu: 'Губы и линии смеха | Meddera',
    titleRo: 'Buze și linii de expresie | Meddera',
    descriptionRu: 'Губы и линии смеха: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Buze și linii de expresie: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: губы и линии смеха.',
    excerptRo: 'Pe scurt: buze și linii de expresie.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-mode-laju-natural',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-mode-laju-natural-beltsy',
    slugRo: 'buze-trend-natural-balti',
    publishedAt: '2026-08-29',
    dateModified: '2026-08-29',
    titleRu: 'Естественный тренд в объёме | Meddera',
    titleRo: 'Trend natural de volum | Meddera',
    descriptionRu: 'Естественный тренд в объёме: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Trend natural de volum: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: естественный тренд в объёме.',
    excerptRo: 'Pe scurt: trend natural de volum.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-podgotovka-k-prazdniku',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-podgotovka-k-prazdniku-beltsy',
    slugRo: 'buze-pregatire-eveniment-balti',
    publishedAt: '2026-08-30',
    dateModified: '2026-08-30',
    titleRu: 'Подготовка к мероприятию | Meddera',
    titleRo: 'Pregătire pentru eveniment | Meddera',
    descriptionRu: 'Подготовка к мероприятию: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Pregătire pentru eveniment: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: подготовка к мероприятию.',
    excerptRo: 'Pe scurt: pregătire pentru eveniment.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-ingirire-prima-saptamina',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-ingirire-prima-saptamina-beltsy',
    slugRo: 'buze-ingrijire-prima-saptamana-balti',
    publishedAt: '2026-08-31',
    dateModified: '2026-08-31',
    titleRu: 'Первая неделя после процедуры | Meddera',
    titleRo: 'Prima săptămână după procedură | Meddera',
    descriptionRu: 'Первая неделя после процедуры: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Prima săptămână după procedură: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: первая неделя после процедуры.',
    excerptRo: 'Pe scurt: prima săptămână după procedură.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-ingirire-lungi-termen',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-ingirire-lungi-termen-beltsy',
    slugRo: 'buze-ingrijire-termen-lung-balti',
    publishedAt: '2026-09-01',
    dateModified: '2026-09-01',
    titleRu: 'Долгосрочный уход | Meddera',
    titleRo: 'Îngrijire pe termen lung | Meddera',
    descriptionRu: 'Долгосрочный уход: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Îngrijire pe termen lung: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: долгосрочный уход.',
    excerptRo: 'Pe scurt: îngrijire pe termen lung.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-voda-plaja-piscina',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-voda-plaja-piscina-beltsy',
    slugRo: 'buze-apa-plaja-piscina-balti',
    publishedAt: '2026-09-02',
    dateModified: '2026-09-02',
    titleRu: 'Губы: вода и солнце | Meddera',
    titleRo: 'Buze: apă și soare | Meddera',
    descriptionRu: 'Губы: вода и солнце: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Buze: apă și soare: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: губы: вода и солнце.',
    excerptRo: 'Pe scurt: buze: apă și soare.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-filler-rari-retragere',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-filler-rari-retragere-beltsy',
    slugRo: 'buze-filler-migrare-rara-balti',
    publishedAt: '2026-09-03',
    dateModified: '2026-09-03',
    titleRu: 'Миграция филлера | Meddera',
    titleRo: 'Migrarea fillerului | Meddera',
    descriptionRu: 'Миграция филлера: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Migrarea fillerului: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: миграция филлера.',
    excerptRo: 'Pe scurt: migrarea fillerului.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-rejuvenare-periferie',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-rejuvenare-periferie-beltsy',
    slugRo: 'buze-intinerire-periferie-balti',
    publishedAt: '2026-09-04',
    dateModified: '2026-09-04',
    titleRu: 'Омоложение контура | Meddera',
    titleRo: 'Întinerire contur | Meddera',
    descriptionRu: 'Омоложение контура: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Întinerire contur: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: омоложение контура.',
    excerptRo: 'Pe scurt: întinerire contur.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-kontur-karandash-korekciya',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-kontur-karandash-korekciya-beltsy',
    slugRo: 'buze-contur-creion-corectie-balti',
    publishedAt: '2026-09-05',
    dateModified: '2026-09-05',
    titleRu: 'Контур и карандаш | Meddera',
    titleRo: 'Contur și creion | Meddera',
    descriptionRu: 'Контур и карандаш: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Contur și creion: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: контур и карандаш.',
    excerptRo: 'Pe scurt: contur și creion.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-gialuron-rascvet',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-gialuron-rascvet-beltsy',
    slugRo: 'buze-acid-hialuronic-degrade-balti',
    publishedAt: '2026-09-06',
    dateModified: '2026-09-06',
    titleRu: 'Рассказ о метаболизме ГК | Meddera',
    titleRo: 'Metabolismul AH în buze | Meddera',
    descriptionRu: 'Рассказ о метаболизме ГК: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Metabolismul AH în buze: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: рассказ о метаболизме гк.',
    excerptRo: 'Pe scurt: metabolismul ah în buze.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-reinjectie-la-luni',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-reinjectie-la-luni-beltsy',
    slugRo: 'buze-reinjectare-luni-balti',
    publishedAt: '2026-09-07',
    dateModified: '2026-09-07',
    titleRu: 'Повторные инъекции по месяцам | Meddera',
    titleRo: 'Reinjectări pe luni | Meddera',
    descriptionRu: 'Повторные инъекции по месяцам: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Reinjectări pe luni: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: повторные инъекции по месяцам.',
    excerptRo: 'Pe scurt: reinjectări pe luni.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-strategie-etape',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-strategie-etape-beltsy',
    slugRo: 'buze-strategie-etape-balti',
    publishedAt: '2026-09-08',
    dateModified: '2026-09-08',
    titleRu: 'Поэтапное увеличение | Meddera',
    titleRo: 'Mărire în etape | Meddera',
    descriptionRu: 'Поэтапное увеличение: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Mărire în etape: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: поэтапное увеличение.',
    excerptRo: 'Pe scurt: mărire în etape.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-dupa-exfoliere-chemical',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-dupa-exfoliere-chemical-beltsy',
    slugRo: 'buze-dupa-exfoliere-chimica-balti',
    publishedAt: '2026-09-09',
    dateModified: '2026-09-09',
    titleRu: 'После химического пилинга | Meddera',
    titleRo: 'După peeling chimic | Meddera',
    descriptionRu: 'После химического пилинга: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'După peeling chimic: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: после химического пилинга.',
    excerptRo: 'Pe scurt: după peeling chimic.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-dupa-laser-lic',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-dupa-laser-lic-beltsy',
    slugRo: 'buze-dupa-laser-fata-balti',
    publishedAt: '2026-09-10',
    dateModified: '2026-09-10',
    titleRu: 'Сочетание с лазером | Meddera',
    titleRo: 'Combinare cu laser | Meddera',
    descriptionRu: 'Сочетание с лазером: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Combinare cu laser: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: сочетание с лазером.',
    excerptRo: 'Pe scurt: combinare cu laser.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-alergie-anestezie',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-alergie-anestezie-beltsy',
    slugRo: 'buze-alergie-anestezie-balti',
    publishedAt: '2026-09-11',
    dateModified: '2026-09-11',
    titleRu: 'Аллергия на анестезию | Meddera',
    titleRo: 'Alergie la anestezie | Meddera',
    descriptionRu: 'Аллергия на анестезию: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Alergie la anestezie: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: аллергия на анестезию.',
    excerptRo: 'Pe scurt: alergie la anestezie.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-compres-reci-prima-or',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-compres-reci-prima-or-beltsy',
    slugRo: 'buze-comprese-reci-prima-ora-balti',
    publishedAt: '2026-09-12',
    dateModified: '2026-09-12',
    titleRu: 'Холод в первый час | Meddera',
    titleRo: 'Rece în prima oră | Meddera',
    descriptionRu: 'Холод в первый час: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Rece în prima oră: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: холод в первый час.',
    excerptRo: 'Pe scurt: rece în prima oră.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'guby-feedback-consultatie',
    kind: 'article',
    clusterId: 'lips',
    slugRu: 'guby-feedback-consultatie-beltsy',
    slugRo: 'buze-feedback-consultatie-balti',
    publishedAt: '2026-09-13',
    dateModified: '2026-09-13',
    titleRu: 'Обратная связь с врачом | Meddera',
    titleRo: 'Feedback după consultație | Meddera',
    descriptionRu: 'Обратная связь с врачом: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Feedback după consultație: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: обратная связь с врачом.',
    excerptRo: 'Pe scurt: feedback după consultație.',
    bodyKey: 'lip-cluster-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
];
