import type { BlogPost } from '@/blog-data/types';

/**
 * Рубрика "Мезотерапия лица в Бельцах" — часть 1 (статьи 1-25)
 */

export const mesotherapyFaceArticlesPart1: BlogPost[] = [
  {
    id: 'mezoterapiya-lica-beltsy-chto-eto',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-beltsy-chto-eto-pokazaniya',
    slugRo: 'mezoterapie-fata-balti-ce-este-indicatii',
    publishedAt: '2026-04-11',
    dateModified: '2026-04-11',
    titleRu: 'Мезотерапия лица в Бельцах: что это и показания | Meddera',
    titleRo: 'Mezoterapia feței în Bălți: ce este și indicații | Meddera',
    descriptionRu: 'Мезотерапия лица: механизм действия, показания, препараты. Консультация в клинике Meddera, Бельцы.',
    descriptionRo: 'Mezoterapia feței: mecanism de acțiune, indicații, preparate. Consultație la clinica Meddera, Bălți.',
    excerptRu: 'Что такое мезотерапия лица и когда она показана.',
    excerptRo: 'Ce este mezoterapia feței și când este indicată.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-preparaty-sostav',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-preparaty-sostav-beltsy',
    slugRo: 'mezoterapie-fata-preparate-compozitie-balti',
    publishedAt: '2026-04-11',
    dateModified: '2026-04-11',
    titleRu: 'Мезотерапия лица: препараты и состав | Meddera',
    titleRo: 'Mezoterapia feței: preparate și compoziție | Meddera',
    descriptionRu: 'Препараты для мезотерапии лица: гиалуроновая кислота, витамины, пептиды. Консультация в Meddera.',
    descriptionRo: 'Preparate pentru mezoterapia feței: acid hialuronic, vitamine, peptide. Consultație la Meddera.',
    excerptRu: 'Какие препараты используются в мезотерапии лица.',
    excerptRo: 'Ce preparate se folosesc în mezoterapia feței.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-kak-prohodit-procedura',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-kak-prohodit-procedura-beltsy',
    slugRo: 'mezoterapie-fata-cum-decurge-procedura-balti',
    publishedAt: '2026-04-11',
    dateModified: '2026-04-11',
    titleRu: 'Мезотерапия лица: как проходит процедура | Meddera',
    titleRo: 'Mezoterapia feței: cum decurge procedura | Meddera',
    descriptionRu: 'Этапы мезотерапии лица: подготовка, инъекции, восстановление. Клиника Meddera, Бельцы.',
    descriptionRo: 'Etapele mezoterapiei feței: pregătire, injecții, recuperare. Clinica Meddera, Bălți.',
    excerptRu: 'Подробное описание этапов процедуры мезотерапии.',
    excerptRo: 'Descriere detaliată a etapelor procedurii de mezoterapie.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-rezultaty-dlitelnost',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-rezultaty-dlitelnost-beltsy',
    slugRo: 'mezoterapie-fata-rezultate-durata-balti',
    publishedAt: '2026-04-12',
    dateModified: '2026-04-12',
    titleRu: 'Мезотерапия лица: результаты и длительность эффекта | Meddera',
    titleRo: 'Mezoterapia feței: rezultate și durata efectului | Meddera',
    descriptionRu: 'Когда виден результат мезотерапии лица и сколько он держится. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Când este vizibil rezultatul mezoterapiei feței și cât ține. Consultație la Meddera, Bălți.',
    excerptRu: 'Результаты мезотерапии и длительность эффекта.',
    excerptRo: 'Rezultatele mezoterapiei și durata efectului.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-protivopokazaniya',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-protivopokazaniya-beltsy',
    slugRo: 'mezoterapie-fata-contraindicatii-balti',
    publishedAt: '2026-04-13',
    dateModified: '2026-04-13',
    titleRu: 'Мезотерапия лица: противопоказания | Meddera',
    titleRo: 'Mezoterapia feței: contraindicații | Meddera',
    descriptionRu: 'Противопоказания к мезотерапии лица: абсолютные и относительные. Консультация в Meddera.',
    descriptionRo: 'Contraindicații la mezoterapia feței: absolute și relative. Consultație la Meddera.',
    excerptRu: 'Кому нельзя делать мезотерапию лица.',
    excerptRo: 'Cui nu se recomandă mezoterapia feței.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-uhod-posle',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-uhod-posle-procedury-beltsy',
    slugRo: 'mezoterapie-fata-ingrijire-dupa-procedura-balti',
    publishedAt: '2026-04-14',
    dateModified: '2026-04-14',
    titleRu: 'Мезотерапия лица: уход после процедуры | Meddera',
    titleRo: 'Mezoterapia feței: îngrijire după procedură | Meddera',
    descriptionRu: 'Рекомендации по уходу после мезотерапии лица. Консультация в клинике Meddera, Бельцы.',
    descriptionRo: 'Recomandări pentru îngrijire după mezoterapia feței. Consultație la clinica Meddera, Bălți.',
    excerptRu: 'Как ухаживать за кожей после мезотерапии.',
    excerptRo: 'Cum să îngrijiți pielea după mezoterapie.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-vozrast',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-vozrast-kogda-nachinat-beltsy',
    slugRo: 'mezoterapie-fata-varsta-cand-incepe-balti',
    publishedAt: '2026-04-15',
    dateModified: '2026-04-15',
    titleRu: 'Мезотерапия лица: с какого возраста можно делать | Meddera',
    titleRo: 'Mezoterapia feței: de la ce vârstă se poate face | Meddera',
    descriptionRu: 'Оптимальный возраст для мезотерапии лица. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Vârsta optimă pentru mezoterapia feței. Consultație la Meddera, Bălți.',
    excerptRu: 'С какого возраста начинать мезотерапию лица.',
    excerptRo: 'De la ce vârstă să începeți mezoterapia feței.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-kurs-procedur',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-kurs-procedur-beltsy',
    slugRo: 'mezoterapie-fata-curs-proceduri-balti',
    publishedAt: '2026-04-16',
    dateModified: '2026-04-16',
    titleRu: 'Мезотерапия лица: курс процедур | Meddera',
    titleRo: 'Mezoterapia feței: curs de proceduri | Meddera',
    descriptionRu: 'Сколько процедур мезотерапии нужно для результата. Консультация в Meddera.',
    descriptionRo: 'Câte proceduri de mezoterapie sunt necesare pentru rezultat. Consultație la Meddera.',
    excerptRu: 'Оптимальный курс мезотерапии лица.',
    excerptRo: 'Cursul optim de mezoterapie a feței.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-bolevye-oshchushcheniya',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-bolevye-oshchushcheniya-beltsy',
    slugRo: 'mezoterapie-fata-senzatii-dureroase-balti',
    publishedAt: '2026-04-17',
    dateModified: '2026-04-17',
    titleRu: 'Мезотерапия лица: больно ли делать | Meddera',
    titleRo: 'Mezoterapia feței: este dureros | Meddera',
    descriptionRu: 'Болевые ощущения при мезотерапии лица и методы обезболивания. Консультация в Meddera.',
    descriptionRo: 'Senzații dureroase la mezoterapia feței și metode de anestezie. Consultație la Meddera.',
    excerptRu: 'Насколько больно делать мезотерапию лица.',
    excerptRo: 'Cât de dureros este să faceți mezoterapia feței.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-otek-sinyaki',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-otek-sinyaki-beltsy',
    slugRo: 'mezoterapie-fata-edem-vanatai-balti',
    publishedAt: '2026-04-18',
    dateModified: '2026-04-18',
    titleRu: 'Мезотерапия лица: отёк и синяки после процедуры | Meddera',
    titleRo: 'Mezoterapia feței: edem și vânătăi după procedură | Meddera',
    descriptionRu: 'Отёк и синяки после мезотерапии: норма или осложнение. Консультация в Meddera.',
    descriptionRo: 'Edem și vânătăi după mezoterapie: normă sau complicație. Consultație la Meddera.',
    excerptRu: 'Что делать с отёком и синяками после мезотерапии.',
    excerptRo: 'Ce să faceți cu edemul și vânătăile după mezoterapie.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-sezon',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-sezon-vremya-goda-beltsy',
    slugRo: 'mezoterapie-fata-sezon-anotimp-balti',
    publishedAt: '2026-04-19',
    dateModified: '2026-04-19',
    titleRu: 'Мезотерапия лица: в какое время года лучше делать | Meddera',
    titleRo: 'Mezoterapia feței: în ce anotimp este mai bine | Meddera',
    descriptionRu: 'Оптимальный сезон для мезотерапии лица. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Sezonul optim pentru mezoterapia feței. Consultație la Meddera, Bălți.',
    excerptRu: 'Когда лучше делать мезотерапию лица.',
    excerptRo: 'Când este mai bine să faceți mezoterapia feței.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-akne-postakne',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-akne-postakne-beltsy',
    slugRo: 'mezoterapie-fata-acnee-postacnee-balti',
    publishedAt: '2026-04-20',
    dateModified: '2026-04-20',
    titleRu: 'Мезотерапия лица при акне и постакне | Meddera',
    titleRo: 'Mezoterapia feței la acnee și postacnee | Meddera',
    descriptionRu: 'Мезотерапия для лечения акне и постакне. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Mezoterapia pentru tratarea acneei și postacneei. Consultație la Meddera, Bălți.',
    excerptRu: 'Как мезотерапия помогает при акне.',
    excerptRo: 'Cum ajută mezoterapia la acnee.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-pigmentaciya',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-pigmentaciya-beltsy',
    slugRo: 'mezoterapie-fata-pigmentare-balti',
    publishedAt: '2026-04-21',
    dateModified: '2026-04-21',
    titleRu: 'Мезотерапия лица от пигментации | Meddera',
    titleRo: 'Mezoterapia feței pentru pigmentare | Meddera',
    descriptionRu: 'Мезотерапия для коррекции пигментации. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Mezoterapia pentru corecția pigmentării. Consultație la Meddera, Bălți.',
    excerptRu: 'Как мезотерапия помогает от пигментных пятен.',
    excerptRo: 'Cum ajută mezoterapia la pete pigmentare.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-morshchiny',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-morshchiny-beltsy',
    slugRo: 'mezoterapie-fata-riduri-balti',
    publishedAt: '2026-04-22',
    dateModified: '2026-04-22',
    titleRu: 'Мезотерапия лица от морщин | Meddera',
    titleRo: 'Mezoterapia feței pentru riduri | Meddera',
    descriptionRu: 'Мезотерапия для коррекции морщин. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Mezoterapia pentru corecția ridurilor. Consultație la Meddera, Bălți.',
    excerptRu: 'Как мезотерапия помогает от морщин.',
    excerptRo: 'Cum ajută mezoterapia la riduri.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-suhaya-kozha',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-suhaya-kozha-beltsy',
    slugRo: 'mezoterapie-fata-piele-uscata-balti',
    publishedAt: '2026-04-23',
    dateModified: '2026-04-23',
    titleRu: 'Мезотерапия лица для сухой кожи | Meddera',
    titleRo: 'Mezoterapia feței pentru piele uscată | Meddera',
    descriptionRu: 'Мезотерапия для увлажнения сухой кожи. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Mezoterapia pentru hidratarea pielii uscate. Consultație la Meddera, Bălți.',
    excerptRu: 'Как мезотерапия помогает сухой коже.',
    excerptRo: 'Cum ajută mezoterapia pielea uscată.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-zhirnaya-kozha',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-zhirnaya-kozha-beltsy',
    slugRo: 'mezoterapie-fata-piele-grasa-balti',
    publishedAt: '2026-04-24',
    dateModified: '2026-04-24',
    titleRu: 'Мезотерапия лица для жирной кожи | Meddera',
    titleRo: 'Mezoterapia feței pentru piele grasă | Meddera',
    descriptionRu: 'Мезотерапия для нормализации жирной кожи. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Mezoterapia pentru normalizarea pielii grase. Consultație la Meddera, Bălți.',
    excerptRu: 'Как мезотерапия помогает жирной коже.',
    excerptRo: 'Cum ajută mezoterapia pielea grasă.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-rasshirennye-pory',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-rasshirennye-pory-beltsy',
    slugRo: 'mezoterapie-fata-pori-dilatati-balti',
    publishedAt: '2026-04-25',
    dateModified: '2026-04-25',
    titleRu: 'Мезотерапия лица от расширенных пор | Meddera',
    titleRo: 'Mezoterapia feței pentru pori dilatați | Meddera',
    descriptionRu: 'Мезотерапия для сужения расширенных пор. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Mezoterapia pentru strângerea porilor dilatați. Consultație la Meddera, Bălți.',
    excerptRu: 'Как мезотерапия помогает от расширенных пор.',
    excerptRo: 'Cum ajută mezoterapia la pori dilatați.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-kuperoz',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lica-kuperoz-beltsy',
    slugRo: 'mezoterapie-fata-cuperoza-balti',
    publishedAt: '2026-04-26',
    dateModified: '2026-04-26',
    titleRu: 'Мезотерапия лица при куперозе | Meddera',
    titleRo: 'Mezoterapia feței la cuperoza | Meddera',
    descriptionRu: 'Мезотерапия для укрепления сосудов при куперозе. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Mezoterapia pentru întărirea vaselor la cuperoza. Consultație la Meddera, Bălți.',
    excerptRu: 'Как мезотерапия помогает при куперозе.',
    excerptRo: 'Cum ajută mezoterapia la cuperoza.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-vokrug-glaz',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-vokrug-glaz-beltsy',
    slugRo: 'mezoterapie-in-jurul-ochilor-balti',
    publishedAt: '2026-04-27',
    dateModified: '2026-04-27',
    titleRu: 'Мезотерапия вокруг глаз | Meddera',
    titleRo: 'Mezoterapia în jurul ochilor | Meddera',
    descriptionRu: 'Мезотерапия для области вокруг глаз. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Mezoterapia pentru zona din jurul ochilor. Consultație la Meddera, Bălți.',
    excerptRu: 'Мезотерапия для омоложения области глаз.',
    excerptRo: 'Mezoterapia pentru întinerirea zonei ochilor.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-sheya-dekolt',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-sheya-dekolt-beltsy',
    slugRo: 'mezoterapie-gat-decolteu-balti',
    publishedAt: '2026-04-28',
    dateModified: '2026-04-28',
    titleRu: 'Мезотерапия шеи и декольте | Meddera',
    titleRo: 'Mezoterapia gâtului și decolteului | Meddera',
    descriptionRu: 'Мезотерапия для омоложения шеи и декольте. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Mezoterapia pentru întinerirea gâtului și decolteului. Consultație la Meddera, Bălți.',
    excerptRu: 'Мезотерапия для шеи и зоны декольте.',
    excerptRo: 'Mezoterapia pentru gât și zona decolteului.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-ruki',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-ruk-beltsy',
    slugRo: 'mezoterapie-maini-balti',
    publishedAt: '2026-04-29',
    dateModified: '2026-04-29',
    titleRu: 'Мезотерапия рук | Meddera',
    titleRo: 'Mezoterapia mâinilor | Meddera',
    descriptionRu: 'Мезотерапия для омоложения кожи рук. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Mezoterapia pentru întinerirea pielii mâinilor. Consultație la Meddera, Bălți.',
    excerptRu: 'Мезотерапия для кожи рук.',
    excerptRo: 'Mezoterapia pentru pielea mâinilor.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-vs-biorevitalizaciya',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-vs-biorevitalizaciya-beltsy',
    slugRo: 'mezoterapie-vs-biorevitalizare-balti',
    publishedAt: '2026-04-30',
    dateModified: '2026-04-30',
    titleRu: 'Мезотерапия vs биоревитализация: в чём разница | Meddera',
    titleRo: 'Mezoterapie vs biorevitalizare: care este diferența | Meddera',
    descriptionRu: 'Разница между мезотерапией и биоревитализацией. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Diferența dintre mezoterapie și biorevitalizare. Consultație la Meddera, Bălți.',
    excerptRu: 'Чем отличается мезотерапия от биоревитализации.',
    excerptRo: 'Cum diferă mezoterapia de biorevitalizare.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-vs-botoks',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-vs-botoks-beltsy',
    slugRo: 'mezoterapie-vs-botox-balti',
    publishedAt: '2026-05-01',
    dateModified: '2026-05-01',
    titleRu: 'Мезотерапия vs ботокс: что выбрать | Meddera',
    titleRo: 'Mezoterapie vs botox: ce să alegeți | Meddera',
    descriptionRu: 'Разница между мезотерапией и ботоксом. Консультация в Meddera, Бельцы.',
    descriptionRo: 'Diferența dintre mezoterapie și botox. Consultație la Meddera, Bălți.',
    excerptRu: 'Чем отличается мезотерапия от ботокса.',
    excerptRo: 'Cum diferă mezoterapia de botox.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lica-kombinaciya-procedur',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-kombinaciya-procedur-beltsy',
    slugRo: 'mezoterapie-combinare-proceduri-balti',
    publishedAt: '2026-05-02',
    dateModified: '2026-05-02',
    titleRu: 'Мезотерапия: комбинация с другими процедурами | Meddera',
    titleRo: 'Mezoterapia: combinare cu alte proceduri | Meddera',
    descriptionRu: 'Можно ли сочетать мезотерапию с другими процедурами. Консультация в Meddera.',
    descriptionRo: 'Se poate combina mezoterapia cu alte proceduri. Consultație la Meddera.',
    excerptRu: 'Комбинация мезотерапии с другими процедурами.',
    excerptRo: 'Combinarea mezoterapiei cu alte proceduri.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
];
