import type { BlogPost } from '@/blog-data/types';

/** Part 2 articles 26–50 — mesotherapy-face */

export const mesotherapyFaceArticlesPart2: BlogPost[] = [
  {
    id: 'mezoterapiya-lico-zona-t',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lico-zona-t-beltsy',
    slugRo: 'mezoterapie-fata-zona-t-balti',
    publishedAt: '2026-09-14',
    dateModified: '2026-09-14',
    titleRu: 'Мезотерапия зоны T | Meddera',
    titleRo: 'Mezoterapia zonei T | Meddera',
    descriptionRu: 'Мезотерапия зоны T: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Mezoterapia zonei T: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: мезотерапия зоны t.',
    excerptRo: 'Pe scurt: mezoterapia zonei t.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-lico-skula-niz',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-lico-skula-niz-beltsy',
    slugRo: 'mezoterapie-pometi-jumatate-inferioara-balti',
    publishedAt: '2026-09-15',
    dateModified: '2026-09-15',
    titleRu: 'Мезотерапия нижней части лица | Meddera',
    titleRo: 'Mezoterapia părții inferioare | Meddera',
    descriptionRu: 'Мезотерапия нижней части лица: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Mezoterapia părții inferioare: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: мезотерапия нижней части лица.',
    excerptRo: 'Pe scurt: mezoterapia părții inferioare.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-amino-peptide',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-amino-peptide-beltsy',
    slugRo: 'mezoterapie-peptide-amino-balti',
    publishedAt: '2026-09-16',
    dateModified: '2026-09-16',
    titleRu: 'Пептиды в мезотерапии | Meddera',
    titleRo: 'Peptide în mezoterapie | Meddera',
    descriptionRu: 'Пептиды в мезотерапии: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Peptide în mezoterapie: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: пептиды в мезотерапии.',
    excerptRo: 'Pe scurt: peptide în mezoterapie.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-vitamine-complex',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-vitamine-complex-beltsy',
    slugRo: 'mezoterapie-vitamine-complex-balti',
    publishedAt: '2026-09-17',
    dateModified: '2026-09-17',
    titleRu: 'Витаминные комплексы | Meddera',
    titleRo: 'Complexe de vitamine | Meddera',
    descriptionRu: 'Витаминные комплексы: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Complexe de vitamine: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: витаминные комплексы.',
    excerptRo: 'Pe scurt: complexe de vitamine.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-kurs-intensiv',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-kurs-intensiv-beltsy',
    slugRo: 'mezoterapie-curs-intensiv-balti',
    publishedAt: '2026-09-18',
    dateModified: '2026-09-18',
    titleRu: 'Интенсивный курс | Meddera',
    titleRo: 'Curs intensiv | Meddera',
    descriptionRu: 'Интенсивный курс: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Curs intensiv: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: интенсивный курс.',
    excerptRo: 'Pe scurt: curs intensiv.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-kurs-podderzhka',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-kurs-podderzhka-beltsy',
    slugRo: 'mezoterapie-curs-mentenanta-balti',
    publishedAt: '2026-09-19',
    dateModified: '2026-09-19',
    titleRu: 'Поддерживающий курс | Meddera',
    titleRo: 'Curs de întreținere | Meddera',
    descriptionRu: 'Поддерживающий курс: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Curs de întreținere: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: поддерживающий курс.',
    excerptRo: 'Pe scurt: curs de întreținere.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-posle-otpusk',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-posle-otpusk-beltsy',
    slugRo: 'mezoterapie-dupa-concediu-balti',
    publishedAt: '2026-09-20',
    dateModified: '2026-09-20',
    titleRu: 'После отпуска на солнце | Meddera',
    titleRo: 'După concediu la soare | Meddera',
    descriptionRu: 'После отпуска на солнце: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'După concediu la soare: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: после отпуска на солнце.',
    excerptRo: 'Pe scurt: după concediu la soare.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-pred-svadba',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-pred-svadba-beltsy',
    slugRo: 'mezoterapie-inainte-nunta-balti',
    publishedAt: '2026-09-21',
    dateModified: '2026-09-21',
    titleRu: 'Перед важным событием | Meddera',
    titleRo: 'Înainte de eveniment | Meddera',
    descriptionRu: 'Перед важным событием: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Înainte de eveniment: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: перед важным событием.',
    excerptRo: 'Pe scurt: înainte de eveniment.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-i-retinoidy-dom',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-i-retinoidy-dom-beltsy',
    slugRo: 'mezoterapie-retinoizi-acasa-balti',
    publishedAt: '2026-09-22',
    dateModified: '2026-09-22',
    titleRu: 'Мезотерапия и домашние ретиноиды | Meddera',
    titleRo: 'Mezoterapie și retinoizi acasă | Meddera',
    descriptionRu: 'Мезотерапия и домашние ретиноиды: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Mezoterapie și retinoizi acasă: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: мезотерапия и домашние ретиноиды.',
    excerptRo: 'Pe scurt: mezoterapie și retinoizi acasă.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-ton-tonalnost',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-ton-tonalnost-beltsy',
    slugRo: 'mezoterapie-ton-uniform-balti',
    publishedAt: '2026-09-23',
    dateModified: '2026-09-23',
    titleRu: 'Выравнивание тона | Meddera',
    titleRo: 'Uniformizarea tonului | Meddera',
    descriptionRu: 'Выравнивание тона: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Uniformizarea tonului: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: выравнивание тона.',
    excerptRo: 'Pe scurt: uniformizarea tonului.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-stress-koza',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-stress-koza-beltsy',
    slugRo: 'mezoterapie-stres-piele-balti',
    publishedAt: '2026-09-24',
    dateModified: '2026-09-24',
    titleRu: 'Стресс и кожа | Meddera',
    titleRo: 'Stres și pielea | Meddera',
    descriptionRu: 'Стресс и кожа: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Stres și pielea: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: стресс и кожа.',
    excerptRo: 'Pe scurt: stres și pielea.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-gipoallergennaya-liniya',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-gipoallergennaya-liniya-beltsy',
    slugRo: 'mezoterapie-linie-hipoalergenica-balti',
    publishedAt: '2026-09-25',
    dateModified: '2026-09-25',
    titleRu: 'Гипоаллергенные протоколы | Meddera',
    titleRo: 'Protocoale hipoalergenice | Meddera',
    descriptionRu: 'Гипоаллергенные протоколы: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Protocoale hipoalergenice: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: гипоаллергенные протоколы.',
    excerptRo: 'Pe scurt: protocoale hipoalergenice.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-sezon-pylecvet',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-sezon-pylecvet-beltsy',
    slugRo: 'mezoterapie-sezon-polen-balti',
    publishedAt: '2026-09-26',
    dateModified: '2026-09-26',
    titleRu: 'Пыльца и кожа | Meddera',
    titleRo: 'Polen și pielea | Meddera',
    descriptionRu: 'Пыльца и кожа: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Polen și pielea: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: пыльца и кожа.',
    excerptRo: 'Pe scurt: polen și pielea.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-primenenie-zimoi',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-primenenie-zimoi-beltsy',
    slugRo: 'mezoterapie-aplicare-iarna-balti',
    publishedAt: '2026-09-27',
    dateModified: '2026-09-27',
    titleRu: 'Мезотерапия зимой | Meddera',
    titleRo: 'Mezoterapia iarna | Meddera',
    descriptionRu: 'Мезотерапия зимой: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Mezoterapia iarna: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: мезотерапия зимой.',
    excerptRo: 'Pe scurt: mezoterapia iarna.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-primenenie-vesnoi',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-primenenie-vesnoi-beltsy',
    slugRo: 'mezoterapie-aplicare-primavara-balti',
    publishedAt: '2026-09-28',
    dateModified: '2026-09-28',
    titleRu: 'Мезотерапия весной | Meddera',
    titleRo: 'Mezoterapia primăvara | Meddera',
    descriptionRu: 'Мезотерапия весной: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Mezoterapia primăvara: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: мезотерапия весной.',
    excerptRo: 'Pe scurt: mezoterapia primăvara.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-primenenie-leto',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-primenenie-leto-beltsy',
    slugRo: 'mezoterapie-aplicare-vara-balti',
    publishedAt: '2026-09-29',
    dateModified: '2026-09-29',
    titleRu: 'Мезотерапия летом | Meddera',
    titleRo: 'Mezoterapia vara | Meddera',
    descriptionRu: 'Мезотерапия летом: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Mezoterapia vara: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: мезотерапия летом.',
    excerptRo: 'Pe scurt: mezoterapia vara.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-primenenie-osenyu',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-primenenie-osenyu-beltsy',
    slugRo: 'mezoterapie-aplicare-toamna-balti',
    publishedAt: '2026-09-30',
    dateModified: '2026-09-30',
    titleRu: 'Мезотерапия осенью | Meddera',
    titleRo: 'Mezoterapia toamna | Meddera',
    descriptionRu: 'Мезотерапия осенью: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Mezoterapia toamna: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: мезотерапия осенью.',
    excerptRo: 'Pe scurt: mezoterapia toamna.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-posle-prostud',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-posle-prostud-beltsy',
    slugRo: 'mezoterapie-dupa-raceala-balti',
    publishedAt: '2026-10-01',
    dateModified: '2026-10-01',
    titleRu: 'После простуды | Meddera',
    titleRo: 'După răceală | Meddera',
    descriptionRu: 'После простуды: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'După răceală: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: после простуды.',
    excerptRo: 'Pe scurt: după răceală.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-i-kuperoz-lechenie',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-i-kuperoz-lechenie-beltsy',
    slugRo: 'mezoterapie-cuperoza-tratament-balti',
    publishedAt: '2026-10-02',
    dateModified: '2026-10-02',
    titleRu: 'Мезотерапия при куперозе | Meddera',
    titleRo: 'Mezoterapie în cuperoză | Meddera',
    descriptionRu: 'Мезотерапия при куперозе: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Mezoterapie în cuperoză: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: мезотерапия при куперозе.',
    excerptRo: 'Pe scurt: mezoterapie în cuperoză.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-glubina-injekcii',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-glubina-injekcii-beltsy',
    slugRo: 'mezoterapie-adancime-injectii-balti',
    publishedAt: '2026-10-03',
    dateModified: '2026-10-03',
    titleRu: 'Глубина инъекций | Meddera',
    titleRo: 'Adâncimea injecțiilor | Meddera',
    descriptionRu: 'Глубина инъекций: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Adâncimea injecțiilor: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: глубина инъекций.',
    excerptRo: 'Pe scurt: adâncimea injecțiilor.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-nadcumbaly',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-nadcumbaly-beltsy',
    slugRo: 'mezoterapie-supraction-balti',
    publishedAt: '2026-10-04',
    dateModified: '2026-10-04',
    titleRu: 'Надбровная зона | Meddera',
    titleRo: 'Zona supraciliară | Meddera',
    descriptionRu: 'Надбровная зона: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Zona supraciliară: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: надбровная зона.',
    excerptRo: 'Pe scurt: zona supraciliară.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-podborodochnyj-treugolnik',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-podborodochnyj-treugolnik-beltsy',
    slugRo: 'mezoterapie-triunghi-barbie-balti',
    publishedAt: '2026-10-05',
    dateModified: '2026-10-05',
    titleRu: 'Подбородочный треугольник | Meddera',
    titleRo: 'Triunghiul bărbiei | Meddera',
    descriptionRu: 'Подбородочный треугольник: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Triunghiul bărbiei: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: подбородочный треугольник.',
    excerptRo: 'Pe scurt: triunghiul bărbiei.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-kombinacia-s-massazhom',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-kombinacia-s-massazhom-beltsy',
    slugRo: 'mezoterapie-combinare-masaj-balti',
    publishedAt: '2026-10-06',
    dateModified: '2026-10-06',
    titleRu: 'С массажем лица | Meddera',
    titleRo: 'Combinată cu masaj facial | Meddera',
    descriptionRu: 'С массажем лица: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Combinată cu masaj facial: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: с массажем лица.',
    excerptRo: 'Pe scurt: combinată cu masaj facial.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-kombinacia-s-chistkoj',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-kombinacia-s-chistkoj-beltsy',
    slugRo: 'mezoterapie-combinare-curatare-balti',
    publishedAt: '2026-10-07',
    dateModified: '2026-10-07',
    titleRu: 'С чисткой лица | Meddera',
    titleRo: 'Combinată cu curățare | Meddera',
    descriptionRu: 'С чисткой лица: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Combinată cu curățare: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: с чисткой лица.',
    excerptRo: 'Pe scurt: combinată cu curățare.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
  {
    id: 'mezoterapiya-zapis-konsultaciya',
    kind: 'article',
    clusterId: 'mesotherapy-face',
    slugRu: 'mezoterapiya-zapis-konsultaciya-beltsy',
    slugRo: 'mezoterapie-programare-consultatie-balti',
    publishedAt: '2026-10-08',
    dateModified: '2026-10-08',
    titleRu: 'Запись на мезотерапию | Meddera',
    titleRo: 'Programare mezoterapie | Meddera',
    descriptionRu: 'Запись на мезотерапию: информационный материал клиники Meddera в Бельцах. Консультация и индивидуальный план.',
    descriptionRo: 'Programare mezoterapie: material informativ, clinica Meddera din Bălți. Consultație și plan individual.',
    excerptRu: 'Коротко о теме: запись на мезотерапию.',
    excerptRo: 'Pe scurt: programare mezoterapie.',
    bodyKey: 'mesotherapy-face-article',
    authorByline: { ru: 'Meddera Beauty Clinic', ro: 'Meddera Beauty Clinic' },
  },
];
